lib/credo/cli.ex
=> Suggest task: alias for :all_priorities missing

lib/credo/cli/output/explain.ex, lib/credo/cli/output/issues_by_scope.ex
Fixes Elixir 1.2 compilation warning.
=> Solution: move the issue.column if-block inside the issue.line_no if-block

test/credo/check/design/alias_usage_test.exs
This adds a unit test for reproducing #54.
=> Multi Alias unit test

lib/credo/check/readability/module_doc.ex, test/credo/check/readability/module_doc_test.exs
=> Do not require @moduledoc for exception modules

.credo.exs, lib/credo/check/warning/bool_operation_on_same_values.ex, test/credo/check/warning/bool_operation_on_same_values_test.exs
It's very similar to the `OperationOnSameValues` check, but `OperationOnSameValues` is about constant results, so I decided to create a separate check.
Not sure if I should use release-0.4.0 branch. Also my english and elixir skills are quite poor, so any feedback is highly appreciated :)
=> Introduce BoolOperationOnSameValues check

README.md, lib/credo/cli.ex, lib/credo/cli/output/summary.ex
See individual commit messages, the pattern of
Enum.reduce(0, &(&1+&2))
can usually be better expressed in my opinion.
=> Minor tweaks to do with summing

lib/credo/check.ex, lib/credo/check/code_helper.ex, lib/credo/check/consistency/space_around_operators/with_space.ex, lib/credo/check/consistency/space_around_operators/without_space.ex, lib/credo/check/find_lint_attributes.ex, lib/credo/check/readability/large_numbers.ex, lib/credo/check/readability/max_line_length.ex, lib/credo/check/readability/trailing_white_space.ex, lib/credo/check/refactor/abc_size.ex, lib/credo/cli.ex, lib/credo/cli/output/explain.ex, lib/credo/cli/output/summary.ex, test/test_helper.exs
New pull request for cleaning up compile warnings. 
Open Issue: https://github.com/rrrene/credo/issues/93
=> V1.3 compile warning

lib/credo/check/readability/large_numbers.ex, lib/credo/check/warning/name_redeclaration_by_assignment.ex
More little changes.
How should I test this so that you can be more confident that my changes don't cause problems?  I do `mix test`, but sometimes wonder whether `mix credo --strict` is running the credo from git or from somewhere else. I'm still learning my way around the Elixir ecosystem!
=> More small clean-ups

README.md
Always find this to be nice to have around, so one can quickly see what the most current version is. Unsure about the positioning among badges, I like it to be first but didn't want to impose my views :)
=> Badge with current version and link to package

.travis.yml
=> Bump elixir to 1.3.1 on travis

lib/credo/check/design/tag_helper.ex, test/credo/check/design/tag_fixme_test.exs, test/credo/check/design/tag_helper_test.exs, test/credo/check/design/tag_todo_test.exs
=> make the tag helper case insensitive (for todo and fixme)

lib/credo/sources.ex, test/credo/sources_test.exs
=> Bring back ability to find path as a list or binary.

lib/credo/cli/output/explain.ex
Just two small grammar things that I noticed.  Thanks much for this tool!
=> Minor grammar fix

lib/credo/check/readability/redundant_blank_lines.ex, test/credo/check/readability/redundant_blank_lines_test.exs
Did this as a custom check for my projects, first custom credo check accomplished! ✅
Perhaps you want this one to be an available option in credo itself? 🙂
=> Check for redundant blank lines

lib/credo/code/sigils.ex, test/credo/check/consistency/space_in_parentheses/with_spaces_test.exs, test/credo/check/consistency/space_in_parentheses/without_space_test.exs
This PR fixes: https://github.com/rrrene/credo/issues/114
=> add: support for heredocs with sigils and test

lib/credo/check/consistency/parameter_pattern_matching.ex, lib/credo/check/consistency/parameter_pattern_matching/position_collector.ex, lib/credo/code/module.ex, test/credo/check/consistency/parameter_pattern_matching_test.exs
This PR addresses this issue/feature request: https://github.com/rrrene/credo/issues/108.
Please let me know if we need to make any doc/code updates before this can be merged.
Would appreciate some assistance/guidance with naming and configuring error messages if you see fit.
Thank you
cc @rrrene
=> Pattern Matching Consistency Check

lib/credo/code/module.ex, test/credo/code/module_test.exs
This PR fixes: https://github.com/rrrene/credo/issues/201
=> Replace return value of nil to return string in Module.name

lib/credo/check/readability/variable_names.ex, lib/credo/code/name.ex, test/credo/check/readability/variable_names_test.exs, test/credo/code/name_test.exs
=> Implement no_case? and add it to variable_names

lib/credo/check_for_updates.ex, mix.lock
=> Fix httpc error during credo version check

lib/credo/check/consistency/space_around_operators/space_helper.ex, test/credo/check/consistency/space_around_operators/without_space_test.exs
fixes https://github.com/rrrene/credo/issues/233
=> add ^-<digit> to the special cases for unary minus

lib/credo/check/readability/parentheses_in_condition.ex
Fixes #225
Thanks to @svoynow for extra help on this one
=> Do not warn about ParenthesesInCondition in one-line `if` call

lib/credo/check.ex, lib/credo/check/consistency/parameter_pattern_matching/position_collector.ex, lib/credo/check_for_updates.ex, lib/credo/cli/output/explain.ex, lib/credo/config.ex, lib/credo/sources.ex
Fixed all Credo warnings in Credo and made pipelines start with raw values now.
=> Fixed all credo warnings

lib/credo/check/readability/string_sigils.ex, test/credo/check/readability/string_sigils_test.exs
So I owed you this one :)
Refs: https://github.com/rrrene/credo/issues/248
=> #248 quotes inside string literals

ISSUE_TEMPLATE.md
There is a typo in the issue template.
=> Fix typo in issue template

test/credo_test.exs
Looks like this test file has been in there since the beginning, but
isn't being used. I guess it should be deleted?
=> Delete unneeded test

test/credo/cli/switches_test.exs
This module was untested, and even though it only has one public
function, and many of those functions are rather simple, there are a
couple things in there that I felt would be helped by having some test
coverage, so I went ahead and added that!
=> Add tests for `Credo.CLI.Switches` module

lib/credo/check/readability/string_sigils.ex, test/credo/check/readability/string_sigils_test.exs
Happy to try and implement a fix for this, adding a failing test for now.
Fixes #305
=> Do not apply StringSigils rule to heredocs

lib/credo/check/readability/string_sigils.ex
=> Fix docs by using checker advice on the checker itself

lib/credo/check/refactor/pipe_chain_start.ex, test/credo/check/refactor/pipe_chain_start_test.exs
=> Allow negative number for pipe chain start

lib/credo/check/refactor/pipe_chain_start.ex, test/credo/check/refactor/pipe_chain_start_test.exs
=> Prevent false positive when initial value to pipe is for loop

lib/credo/check/readability/module_names.ex, test/credo/check/readability/module_names_test.exs
=> Fix false positive for Credo.Check.Readability.ModuleNames

.credo.exs, lib/credo/check/readability/space_after_commas.ex, test/credo/check/readability/space_after_commas_test.exs
Creates a new readability check SpaceAfterCommas and resolves https://github.com/rrrene/credo/issues/324 (as long as we're good with a readability check).
Let me know if I've missed something or my Elixir is rusty and I'll fix it :-)
=> Add check for spaces after commas

lib/credo/check/readability/trailing_white_space.ex, lib/credo/code/strings.ex, test/credo/check/readability/trailing_white_space_test.exs
Resolves https://github.com/rrrene/credo/issues/315
=> Allow trailing whitespace in heredocs

lib/credo/check/warning/lazy_logging.ex, lib/credo/check/warning/logging.ex, test/credo/check/warning/logging_test.exs
=> Ensures laziness of Logger calls

lib/credo/config_builder.ex
=> respect `strict: true` in .credo.exs

lib/credo/code/sigils.ex
to reduce compiler warnings
fixes #383
=> Reduce amount of removable_sigils

.credo.exs, lib/credo/check/warning/raise_inside_rescue.ex, test/credo/check/warning/raise_inside_rescue_test.exs
=> Emit a warning for raise inside rescue

lib/credo/check/refactor/long_quote_blocks.ex
Found it... Fixes issue [#390](https://github.com/rrrene/credo/issues/390).
=> Fix LongQuoteBlocks message

lib/credo/check/design/alias_usage.ex
Added Date, DateTime, NaiveDateTime, Time and Registry.
=> Add new elixir modules to AliasUsage exceptions

README.md
=> Add bunt instructions in stand alone installation

.travis.yml
1.4.5 is out now, as is OTP 20!
=> Update CI config to test new Elixir and OPT version

test/credo/check/consistency/parameter_pattern_matching/collector_test.exs, test/credo/check/consistency/space_around_operators_test.exs
=> Rename some modules in tests for consistency

lib/credo/check/warning/raise_inside_rescue.ex, test/credo/check/warning/raise_inside_rescue_test.exs
=> Handle 'raise inside rescue' for implicit try

lib/credo/check/consistency/space_around_operators/collector.ex, test/credo/check/consistency/space_around_operators/collector_test.exs
=> Correctly handle @module_attrs when counting spaces around binary operators

lib/credo/check/refactor/pipe_chain_start.ex, test/credo/check/refactor/pipe_chain_start_test.exs
=> Allow anonymous functions to be piped as raw values

lib/credo/check/warning/unused_function_return_helper.ex, test/credo/check/warning/unused_list_operation_test.exs
=> Handle :fn properly in nested function calls for unused returns

lib/credo/check/readability/prefer_unquoted_atoms.ex, test/credo/check/readability/prefer_unquotes_atoms_test.exs
=> Add prefer unquoted atoms check

lib/credo/cli/output/issues_by_scope.ex
Fixes https://github.com/rrrene/credo/issues/432
I couldn't find any example of UI test. @rrrene Could you give me a tip how to handle test case for such scenario.
My idea is to add a helper function in test_helper module - to print message as string and match it against expectation.
=> Fix underlining in `list` mode

lib/credo/check/readability/module_names.ex, test/credo/check/readability/module_names_test.exs
=> Filter module names which can be converted to strings

lib/credo/check/refactor/match_in_condition.ex, test/credo/check/refactor/match_in_condition_test.exs
=> Tried to fix #535

lib/credo/check/consistency/space_around_operators.ex, lib/credo/check/design/alias_usage.ex, lib/credo/check/design/duplicated_code.ex
Some parameters explanations were missing from the @explanation definition.
=> Added missing explanations for some parameters

README.md
Thank you for the great tool!
I am adding Codacy to the readme section for automated code review tools.
This way, more people can use credo analysis out of the box, for free.
=> Add Codacy to automated code review integrations

.credo.exs, lib/credo/check/refactor/with_clauses.ex, test/credo/check/refactor/with_clauses_test.exs
=> Add the WithClauses refactor check

.credo.exs
After finding https://github.com/rrrene/credo/issues/221, I expected this to be listed as available
=> Add `SinglePipe` to list of opt-in checks

lib/credo/check/refactor/negated_is_nil.ex, test/credo/check/refactor/negated_is_nil_test.exs
@rrrene, like we discussed here: https://github.com/rrrene/credo-proposals/issues/49
Please let me know if this would add any value! If not, no worries!
=> Implement NegatedIsNil check.

.github/workflows/bugfix-detector.yml, .github/workflows/bugfix-reproducer.yml, lib/credo/code/charlists.ex, test/credo/code/charlists_test.exs, test/test_if_tests_fail_after_resetting_lib.sh
=> Fix charlists replacing

lib/credo/check/readability/trailing_white_space.ex, test/credo/check/readability/trailing_white_space_test.exs
Added a test that failed before fixing the issue.
=> Fix regex with unicode support Closes #757

lib/credo/check/refactor/negated_is_nil.ex
=> Add example to explanation - negated is nil check - Closes #748

lib/credo/check.ex
Getting warnings on master about mismatched types. Updated types to reflect values in use.
=> Fix mismatch in base_priority type

.github/workflows/bugfix-reproducer.yml, .github/workflows/ci-workflow.yml, .github/workflows/compatibility-elixir.yml, .github/workflows/compatibility-phoenix.yml
Extracted from https://github.com/rrrene/credo/pull/785 and expanded upon.
References:
- https://github.com/actions/checkout/blob/main/CHANGELOG.md
- https://github.com/actions/setup-elixir/releases
=> update checkout and setup-elixir GitHub Actions to their latest versions

.credo.exs, lib/credo/check/readability/impl_true.ex, test/credo/check/readability/impl_true_test.exs
Add check for @impl true to change to @impl MyBehaviour
=> Add check for @impl true to change to @impl MyBehaviour

lib/credo/build_info.ex
Close #835 
Let me know if this is enough to take care of #835, or should I take other approach.
=> Wrap System.cmd call on try rescue when verify git presence

lib/credo/check/readability/predicate_function_names.ex, test/credo/check/readability/predicate_function_names_test.exs
Changing predicate rules to check funcions with arity greater than 0.
I created three more tests too
=> Changing predicate to arity

lib/credo/check/refactor/redundant_with_clause_result.ex, test/credo/check/refactor/redundant_with_clause_result_test.exs
=> Fix RedundantWithClauseResult

.github/workflows/ci-workflow.yml, lib/credo/code/interpolation_helper.ex, test/credo/code/interpolation_helper_test.exs, test/credo/code_test.exs, test/test_helper.exs
This PR should fix #881 - let's see if GitHub Actions approves the changes.
=> Fix code cleaning

lib/credo/code.ex
related to https://github.com/rrrene/credo/issues/893
https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_tokenizer.erl#L154
=> Elixir 1.13 support

lib/credo/code.ex
There are some failing tests that seem related to 1.13, but I'm not confident whether fixing them is required.
=> Support elixir 1.13 tokenizer results

lib/credo/check/refactor/reject_reject.ex
Just saw this in the check output.
=> fix refactoring example

lib/credo/check/readability/parentheses_in_condition.ex, test/credo/check/readability/parentheses_in_condition_test.exs
=> Fix #919: add `:in_op` to parentheses in conditon

lib/credo/check/refactor/apply.ex, test/credo/check/refactor/apply_test.exs
=> Update apply check

lib/credo/check.ex, lib/credo/cli/command/list/list_output.ex, lib/credo/cli/command/list/output/sarif.ex, lib/credo/cli/command/suggest/output/sarif.ex, lib/credo/cli/command/suggest/suggest_output.ex, lib/credo/cli/output/formatter/sarif.ex, test/fixtures/integration_test_config/.sarif.exs, test/integration/suggest_test.exs
Please see discussion thread: https://github.com/rrrene/credo-proposals/issues/58
@michaelcfanning @EasyRhinoMSFT @rrrene
=> Add SARIF support

lib/credo/check/refactor/apply.ex, test/credo/check/refactor/apply_test.exs
An attempt to fix https://github.com/rrrene/credo/issues/993
=> fix: False positive on Credo.Check.Refactor.Apply when piped

lib/credo/check/consistency/collector.ex, lib/credo/check/consistency/exception_names.ex, test/credo/check/consistency/exception_names_test.exs
#969 
Seems like those changes weren't merged.
=> Supress issues for single consistency match

lib/credo/check/readability/alias_order.ex, test/credo/check/readability/alias_order_test.exs
This supercedes #1006 and addresses https://github.com/rrrene/credo/issues/1007
EDIT: @rrrene ignore earlier comment, I added support for alias grouping
=> Case sensitive alias order

lib/credo/check/consistency/unused_variable_names/collector.ex, test/credo/check/consistency/unused_variable_names_test.exs
Fixes https://github.com/rrrene/credo/issues/1175
=> Fix duplicated suggestions with UnusedVariableNamesTest

lib/credo/check/readability/nested_function_calls.ex, test/credo/check/readability/nested_function_calls_test.exs
Added a guard for all typespec attributes, closes: #1170
=> Fix false positive for NestedFunctionCalls

README.md
We closed the business. Thanks @rrrene for all the support! :)
=> Remove SourceLevel mention on README
