README.md

Hey there,
I noticed that the readme recommends you install credo without specifying which environment it will run in - to me it seems that credo should only ever be run in development and test environments, and is not particularly useful in production.

Credo should not be a production dependency

---

.credo.exs

This way, if you add credo to the top level of an umbrella app and have it run
over all source files.

Add app/ to default config's included files

---

lib/credo/check/design/duplicated_code.ex
lib/credo/check/readability/trailing_white_space.ex
lib/credo/cli/output/issues_short_list.ex
lib/credo/config.ex

Latest Elixir master introduces additional compilation warnings.
This patch fixes some of them:
---
lib/credo/check/design/duplicated_code.ex:122:
warning: you are piping into a function call without parentheses, which is ambiguous. Please wrap the function you are piping into in parentheses. For example:
foo 1 |> bar 2 |> baz 3
Should be written as:
foo(1) |> bar(2) |> baz(3)
---
lib/credo/check/readability/trailing_white_space.ex:20:
warning: an expression is always required on the right side of ->. Please provide a value after ->
---
lib/credo/cli/output/issues_short_list.ex:15:
warning: an expression is always required on the right side of ->. Please provide a value after ->
---
lib/credo/config.ex:87:
warning: default arguments in from_exs/3 are never used

Problem: Compilation errors on Elixir 1.2.0-dev

---

test/credo/check/consistency/helper_test.exs

Running `mix test` produces the warning:
```
test/credo/check/consistency/helper_test.ex does not match "*_test.exs" and won't be loaded
```
Solution:
1. Rename `helper_test.ex` to `helper_test.exs`
2. Rename test to `Credo.Check.Consistency.HelperTest`
3. Fix alias to `Credo.Check.Consistency.Helper`
4. Fix asserts to reflect changed return format of `most_picked_prop_value/1`

Problem: Credo.Consistency.HelperTest was not executed

---

lib/credo/check/readability/predicate_function_names.ex

The message didn't fully explain what would flag a function as having poor predicate naming.

Add note that predicates should not start with 'is'

---

lib/credo/check/readability/max_line_length.ex

Describe default behaviour for function definitions and strings.

---

lib/credo/cli/output.ex

When running `mix credo --one-line` both `readability checks` and
`refactoring checks` were tagged with [R].
This commit change the `refactoring` tags to [F] in order to avoid
ambiguity and help users who would like to feed `credo` 's output to
other programs.
Closes #29

Change refactor tag @ `--one-line` from [R] to [F]

---

lib/credo/cli/command/help.ex

Inserts an explicit `nil` value instead of an implicit `nil` value where a catch-all clause matches and only has a comment in place.

Fox minor clause warning for a missing value

---

lib/credo/cli/output/explain.ex
lib/credo/cli/output/issue_helper.ex
lib/credo/cli/output/issues_by_scope.ex
lib/credo/cli/output/issues_short_list.ex

The fixed `:white` color makes credo a bit unhelpful when using light backgrounds:
Using the `:default_color` leaves this up for your terminal to decide:

Do not use `:white` as the color for filenames.

---

lib/credo/cli.ex
lib/mix/tasks/credo.ex

This PR fixes #41.
I would like to refactor much more by completely moving those stuff in to a “sublib” which is then used by cli and mix instead of the current situation where mix is just a wrapper to cli. But unfortunately I'm missing the necessary time.

Fix `mix do` behaviour

---

lib/credo/code/sigils.ex
test/credo/code/sigils_test.exs

i fixed UnicodeConversionError occurs when a comment has UTF 8 character (ex : ```↑```, ```エリクサー```).
Thanks

fixed : UnicodeConversionError when a comment has UTF 8 character

---

mix.exs

Credo errors with Elixir versions less than v1.1 because the tokenizer did not supply column positions until v1.1. 
Here is the output of the error when running `mix credo` on Elixir v1.0.5.
```
** (MatchError) no match of right hand side value: {:ok, 3, [{:identifier, 1, :defmodule}, {:aliases, 1, [:CredoTest]}, {:do, 1}, {:eol, 1}, {:end, 2}, {:eol, 2}]}
lib/credo/code.ex:60: Credo.Code.to_tokens/1
lib/credo/check/consistency/space_around_operators/with_space.ex:16: Credo.Check.Consistency.SpaceAroundOperators.WithSpace.property_values_for/2
lib/credo/check/consistency/helper.ex:152: anonymous fn/4 in Credo.Check.Consistency.Helper.collect_property_values/3
(elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
lib/credo/check/consistency/helper.ex:144: …
```

Set minimum Elixir version to 1.1

---

lib/credo/cli/output/explain.ex

Fixes #67.
The filters were able to remove all issues, leading to `[] |> List.first` on line 46.

Fix cryptic error when no issues are in given line

---

RELEASING.md

Something that was bothering me when I opened up the rendered `RELEASING.md` file on GitHub 😄 
* [Before](https://github.com/remiprev/credo/blob/master/RELEASING.md)
* [After](https://github.com/remiprev/credo/blob/18cc7377a7602e80109dfc0c15707625da93d2e5/RELEASING.md)

Fix Markdown indent issue in RELEASING.md

---

lib/credo/check/code_helper.ex
lib/credo/check/design/duplicated_code.ex
lib/credo/check/warning/bool_operation_on_same_values.ex
lib/credo/check/warning/operation_on_same_values.ex
test/credo/check/code_helper_test.exs
test/credo/check/design/duplicated_code_test.exs
test/credo/check/warning/bool_operation_on_same_values_test.exs
test/credo/check/warning/operation_on_same_values_test.exs

I've noticed that `OperationOnSameValues` and `BoolOperationOnSameValue` checks don't work when `lhs` and `rhs` are on different lines and `metadata` values inside ast are different.
Not sure if `CodeHelper` is good place for `remove_metadata`. Feedback is highly appreciated!

Ignore metadata in OperationOnSameValues and BoolOperationOnSameValue checks

---

lib/credo/check/code_helper.ex
lib/credo/check/consistency/helper.ex
lib/credo/check/design/duplicated_code.ex
lib/credo/check/design/tag_helper.ex
lib/credo/check/readability/max_line_length.ex
lib/credo/check/readability/trailing_white_space.ex
lib/credo/check/refactor/abc_size.ex
lib/credo/cli/output/explain.ex
lib/credo/cli/output/issue_helper.ex
lib/credo/cli/output/issues_by_scope.ex
lib/credo/cli/output/issues_grouped_by_category.ex
lib/credo/cli/output/summary.ex
lib/credo/cli/output/ui.ex
lib/credo/code/scope.ex
lib/credo/priority.ex
test/credo/cli/output/ui_test.exs

This came about because I ran `credo` on itself as an experiment, and these seemed like harmless changes to eliminate a whole class of messages.

Minor clean-ups on credo

---

lib/credo/exs_loader.ex
test/credo/exs_loader_test.exs

Hi @rrrene, I was trying to load a config in safe mode, using default credo config and it was not working because of module names. 
What do you think about this change?

allow module names when parsing config in safe mode

---

lib/credo/check/consistency/exception_names.ex
lib/credo/check/readability/large_numbers.ex
lib/credo/check/readability/module_names.ex
lib/credo/check/refactor/abc_size.ex
lib/credo/check/refactor/nesting.ex
lib/credo/check/warning/name_redeclaration_by_case.ex
lib/credo/check/warning/name_redeclaration_by_def.ex
lib/credo/check/warning/name_redeclaration_by_fn.ex
lib/credo/check/warning/unused_enum_operation.ex
lib/credo/cli/output/explain.ex
lib/credo/cli/output/issue_helper.ex
lib/credo/cli/output/issues_by_scope.ex
lib/credo/cli/output/ui.ex
lib/credo/sources.ex

This contains changes which I think are uncontroversial to reduce the number of "violations" in the `credo` source itself.

Release 0.4.0 - reduce number of messages from `mix credo --strict` on itself

---

lib/credo/priority.ex

I'm not sure what should go in `@moduledoc` but this eliminates all the other warnings for `priority.ex`.
I was puzzled by the long lines which snuck past `credo` mentioned in the commit message for eb49a29, but as my goal is to eliminate warning messages I'll not dig into that *now* 😀

Release 0.4.0 - cleanup lib/credo/priority.ex

---

lib/credo/cli/command/explain.ex

Currently (0.4.3) `mix credo explain` will fail because of a missing function clause. Running `mix credo explain --help` suggests that files are optional ( `[path_line_no_column]` ). I'm not sure what future plans are, but to prevent this error from showing up, this fix prints help in case of no supplied files, with a slightly different help message to prevent confusion.
Just FYI, this is the current error (first part):
```
$ mix credo explain
** (FunctionClauseError) no function clause matching in Credo.CLI.Command.Explain.run/2
lib/credo/cli/command/explain.ex:15: Credo.CLI.Command.Explain.run([], %Credo.Config{all: false, check_for_updates: true, checks: [{Credo.Check.Consistency.ExceptionNames}, ... etc .. help: false })
lib/credo/cli.ex:58: Credo.CLI.main/1
(mix) lib/mix/cli.ex:58: …
```

Circumvent exception for explain without file

---

lib/credo/check/readability/parentheses_in_condition.ex
test/credo/check/readability/parentheses_in_condition_test.exs

Adds a check for parentheses in `if` or `unless` conditions.
Moves existing `Credo.Check.Refactor.ParenthesesInConditionTest` to `Credo.Check.Readability`.
Fixes #78

Checks for parentheses in if/unless conditions

---

lib/credo/check/readability/max_line_length.ex
test/credo/check/readability/max_line_length_test.exs

Add option to ignore `@spec` definitions when getting line length
errors.
Fix #120

Add `ignore_specs` option to max_line_length

---

lib/credo/check/readability/large_numbers.ex
test/credo/check/readability/large_numbers_test.exs

René, I'm not sure if this *should* be merged into `credo`, I think it illustrates some useful ideas.
I was irritated by the long number checks telling me that 0xFFFF might be better written as 65_535, and by the poor formatting of the fractional part of long floats in error messages.
To do a proper fix we need to use elixir 1.3.2 or 1.4.x where https://github.com/elixir-lang/elixir/commit/301aa6eddce60c02a7fd11a7c1426aec97338878 has taken effect, otherwise we need some heuristic to figure out where the number tokens come from.  Believe that being able to reliably get the source text will be useful anyway.
So the basic changes were:
- don't expect _ in the fractional part of floating point numbers
- don't check non-decimal numbers
Let me know what you think, and how we can move this …

Better long number checking

---

lib/credo/check/readability/large_numbers.ex
test/credo/check/readability/large_numbers_test.exs
test/test_helper.exs

Minor cleanups prompted by testing with 1.3.2-dev.
* Compare version against 1.3.2-dev so that we can test against the -dev
version
* Remove special data for pre-1.3.2 test cases, tag the ones which
needed special data with `@tag needs_elixir: "1.3.2"`
* Add check in test helper to set the `needs_elixir: "1.2.3"` exclusion
if necessary.

Last tweaks to large numbers testing

---

lib/credo/cli/command/explain.ex
lib/credo/cli/command/list.ex
lib/credo/cli/command/suggest.ex

Making use of [`Enum.partition/2`](http://elixir-lang.org/docs/stable/elixir/Enum.html#partition/2) we avoid looping twice over the list of source files when filtering out invalid source files. Apart from improved legibility, in a sufficiently large list these changes may even mean a perceptible performance improvement.

Improve source file loading

---

lib/credo/check/design/alias_usage.ex
lib/credo/code/module.ex
lib/credo/code/name.ex
test/credo/check/design/alias_usage_test.exs
test/credo/code/module_test.exs
test/credo/code/name_test.exs

Hello, René!
This is a PR to resolve issue #76 related to `Ambiguos alias usage`. I have done the following changes here:
- new function for `alias_usage.ex` to catch conflicts with module dependencies specified in issue description;
- `alias_usage.ex` refactoring;
- new functions `aliases` and `modules` for `Credo.Code.Module` public API and tests for these functions;
- new functions for `Credo.Code.Name` API and tests for these functions.
Thanks in advance for your time!

issue/76 Ambiguous alias usage

---

lib/credo/sources.ex
test/credo/sources_test.exs

Currently, a minor misconfiguration in the list of source files to be checked can lead to unwanted behavior. Intersecting glob patterns will make the engine process files **multiple times**, which in turn will trigger some issues of the `Credo.Check.Design.DuplicatedCode` type.

Prevent Credo from processing the same file multiple times

---

lib/credo/check/readability/no_parentheses_when_zero_arity.ex
test/credo/check/readability/no_parentheses_when_zero_arity_test.exs

This will trigger a warning on function heads that have no arguments, but do have parentheses.
Interesting to have that in credo? 😊

Checks no parentheses exists on zero arity functions

---

lib/credo/check/readability/module_doc.ex
test/credo/check/readability/module_doc_test.exs

Adding accumulator to keep track if we should continue the ast prewalk when an ignored module is found.
fix #165

Stop moduledoc check for child nodes in ignored modules

---

lib/credo/cli/output/summary.ex

Simply ignore the 'showing priority issues' string if no issues are found
fix 166

Do not print 'showing priority issues' when no issues are found

---

lib/credo/sources.ex

"stdin" annotation can't be overridden since 0.3.13 with default config.
Today I spent quite some time trying to figure out why flycheck-credo doesn't work.
As it turned out this https://github.com/rrrene/credo/blob/master/.credo.exs#L23 doesn't work with this https://github.com/rrrene/credo/blob/master/lib/credo/sources.ex#L19

Don't care about excluded files when reading stdin

---

lib/credo/check/readability/parentheses_in_condition.ex
test/credo/check/readability/parentheses_in_condition_test.exs

Fixes #164 
I added some more tests to account for grouping on either side of the outer operation and for one lined statements.
This keeps track of the condition that had the grouped logic. 
Before 
```
echo "if (thing && other_thing), do: something" | mix credo --read-from-stdin
Checking 1 source file ...
Code Readability                                                              
┃ 
┃ [R] ↗ The condition of `` should not be wrapped in parentheses.
┃       stdin:1 ()
```
After
```
echo "if (thing && other_thing), do: something" | mix credo --read-from-stdin
Checking 1 source file ...
Code Readability                                                              
┃ 
┃ [R] ↗ The condition of `if` should not be wrapped in parentheses.
┃       stdin:1:1 ()
```

Fix false positive with grouped logic in if statement

---

lib/credo/check/refactor/abc_size.ex
test/credo/check/refactor/abc_size_test.exs

@rrrene created a new head for `traverse_abc` in order to omit counting of Map/Struct record access using dot notation inside of a function.  Please let me know if there was an edge case I have missed and need to rework the solution or if the patch needs further explanation.
This issue fixes https://github.com/rrrene/credo/issues/171.

Add new function head for #traverse_abc in abc_size.ex(fixes issue #171)

---

lib/credo/check/refactor/pipe_chain_start.ex

This fixes https://github.com/rrrene/credo/issues/182.
This PR adds `:&` to the list of atoms in order to support variable capture at the start of the pipe chain .

Add ampersand support to atom list in pipe_chain_start

---

lib/credo/check/refactor/pipe_chain_start.ex
test/credo/check/refactor/pipe_chain_start_test.exs

This PR fixes and address the conversation here: https://github.com/rrrene/credo/issues/182
Added support for list concatenation, string concatenation, and list subtraction for the pipe chain start rule.

add: list concat, list subtraction, and string concat for pipeline

---

lib/credo/cli/output/summary.ex

This PR fixes: https://github.com/rrrene/credo/issues/166
Added new function head to `summary.ex` to show the user `Use --strict to show all issues, --help for options.` if credo does not produce any errors and the user does NOT input `--strict` as an argument.

update: summary.ex with new function head for #print_priority_hint

---

lib/credo/code.ex
test/credo/code_test.exs

When one of the files processed by credo is encoded in anything other than utf-8, credo will crash:
```
$ mix credo
** (UnicodeConversionError) invalid encoding starting at <<233, 34, 10>>
(elixir) lib/string.ex:1748: String.to_charlist/1
(elixir) lib/code.ex:266: Code.string_to_quoted/2
lib/credo/code.ex:62: Credo.Code.ast/2
lib/credo/source_file.ex:59: Credo.SourceFile.with_ast/1
(elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
(elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
lib/credo/cli/command/suggest.ex:41: anonymous fn/1 in Credo.CLI.Command.Suggest.load_and_validate_source_files/1
(stdlib) timer.erl:166: :timer.tc/1
```
With these changes, credo will now gracefully skip over those files:
```
$ mix credo
Some source files could not be parsed correctly and are …
```

Make sure credo does not crash on non-utf8 files

---

.credo.exs
lib/credo/cli.ex
lib/credo/config.ex

It was requested to be able to set `--strict` in the config file, so I've added
that ability here. I have also updated the documentation to make it apparent
that this is a setting that is available to the user.
I had a hard time finding tests for similar functionality, so I haven't added
any tests for this feature. I'd love to do that, though, if someone can point me
in the right direction as to how this should be tested.
I've tried this on my local machine and seen that it works, but I'm also fairly
certain that the implementation that I have isn't consistent with the rest of
the application. If folks have any other guidance on how I can make my
implementation better, I'd be happy to hear it!
Resolves #168

Add ability to specify `strict` in `.credo.exs` config file

---

lib/credo/check/runner.ex

I made a large change to my codebase and credo's runner started crashing on me. While the debug stack told me where in credo I was crashing, I wasn't able to figure out what code of mine was causing the issue.
With this change, I was able to track down the file that was breaking things for me.
Obviously, I could have gotten the same debug line by turning off the "crash_on_error" setting, but I didn't know about it and don't really want to have to flip config settings to debug.
---------------
Sorry for the second PR. For some reason, force pushing my branch disabled my ability to reopen the original PR

Always print where check runner errors happened to help with debugging

---

README.md

Since 0.4 does not work properly with the Hex v0.14.0. See #210.
_Update:_
I did see that v0.4.14 addresses this issue for v0.4, but still seems like a good idea to have new projects use 0.5.

Update README installation instructions to v0.5

---

lib/credo/cli/output/explain.ex

Currently if you have an issue on the last line (or second to last) of your code and you do an explain, it will raise a match error. For example:
```
$  mix credo lib/cards.ex:22
[..]
__ CODE IN QUESTION
┃ 
┃    20   end
┃    21 end
┃    22 IO.inspect(2)
┃       ^^^^^^^^^^
┃    23 
** (MatchError) no match of right hand side value: nil
lib/credo/cli/output/explain.ex:197: Credo.CLI.Output.Explain.print_source_line/5
lib/credo/cli/output/explain.ex:162: Credo.CLI.Output.Explain.print_issue/3
(elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
(elixir) lib/enum.ex:651: Enum.each/2
lib/credo/cli/command/explain.ex:23: Credo.CLI.Command.Explain.run/2
lib/credo/cli.ex:58: Credo.CLI.main/1
(mix) lib/mix/task.ex:296: Mix.Task.run_task/3
(mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
``` …

Fix explain on last line issue raises a match error

---

lib/credo/check/readability/redundant_blank_lines.ex
test/credo/check/readability/redundant_blank_lines_test.exs

If you had a file without ANY blank line, RedundantBlankLines would raise because `consecutive_lines([], _)` was returning `:false` and that value was being piped into an `Enum.map/2`
An example of file that would trigger the error behaviour without this patch:
```elixir
defmodule MyApp do
end
````

Fix RedundantBlankLines raising when file doesn't have blank lines

---

test/credo/check/warning/operation_on_same_values_test.exs

As discussed in #218. Moving this case down to expected warning assertion
Closes #218 
All tests passing once again 🎉

Update OperationOnSameValuesTest to allow new case

---

lib/credo/check/consistency/parameter_pattern_matching/position_collector.ex
test/credo/check/consistency/parameter_pattern_matching_test.exs

`position_collector.ex` checked the parameter definitions of the files and flat_mapped this. But when the input ast node was either a `def` without bindings or a `defp` or `defmacro`, it would return `nil` .
Example of input file that would have triggered an error:
```elixir
defmodule Foo do
def bar do
:bar
end
defp baz(foo) do
foo
end
end
```

Fix bug on ParameterPatternMatchingTest on private funs and funs with no binding

---

lib/credo/cli.ex
lib/credo/config.ex

We implemented the ability to set a `strict: true` config in the `.credo.exs`
file for a project, but when we did that we didn't implement any way to
override that with a command line flag. In this commit we're adding that
ability to override that setting with a `--no-strict` flag so you don't need to
edit that file to turn off `strict` mode for just a single run.
Closes #214

Add ability to use `--no-strict` command line flag

---

lib/credo/check/code_helper.ex
lib/credo/code/block.ex
lib/credo/exs_loader.ex

Some of the typeguards would be never run, or return false, since they
were testing for a subset of the previously called `is_atom/1`
In fact `true` and `false` as well as `nil` are just atoms.

cleanup type-guards

---

lib/credo/cli.ex
lib/credo/cli/switches.ex

We had a lot of private methods that all were essentially part of the same
operation - setting the `Config` struct - part of a module that had a lot going
on, so I extracted them all to a new module to group that behavior together and
hopefully make it a little easier to understand both modules now.

Refactor `cli.ex` to extract module for setting config

---

.credo.exs
lib/credo/check/refactor/variable_rebind.ex
test/credo/check/refactor/variable_rebind_test.exs

This will check for multiple declaration of the same variable within a do block. 
For example,
```elixir
defmodule CredoSampleModule do
def some_function() do
a = 1
a = 2
end
end
```
would trigger a warning because `a` is declared twice.

Implemented check for variable rebinding

---

lib/credo/check.ex
lib/credo/check/readability/large_numbers.ex
lib/credo/check/runner.ex
lib/credo/cli/output/summary.ex
lib/credo/config.ex

We have some checks that don't behave entirely as expected for some older
versions of Elixir, and we want to deprecate (and eventually remove) thos
checks for those versions. This is the first very quick and _very_ dirty spike
on a way to do that so we can start a discussion around how we want to handle
this process.
This is related to #229 and will hopefully give us a starting point for discussion.

Add deprecation and exclusion of checks by Elixir version

---

.credo.exs
lib/credo/check/readability/prefer_implicit_try.ex
test/credo/check/readability/prefer_implicit_try_test.exs

We don't need to explicitly use `try` inside function definitions, and this
check will raise low priority issues when `try` is explicitly used.
Closes #224

Add check for prefering implicit `try`

---

lib/credo/check_for_updates.ex

Changed `String.to_charlist` function to `String.to_char_list`.
Since `to_charlist` is not available in the `elixir < 1.3`.
`to_char_list` will be deprecated in `1.5`.
To see the related issue, see: https://github.com/elixir-lang/elixir/issues/4909
Closes #272

Changes the way String is casted to Charlist in Autoupdate module

---

lib/credo/check/readability/prefer_implicit_try.ex
test/credo/check/readability/prefer_implicit_try_test.exs

I realized that the implementation that I had for the
`PreferImplicitTry` check was incomplete and wouldn't raise an issue
when used in private functions. That's been added here, as well as a
test to cover that additional case.

Fix `prefer_implicit_try` check

---

lib/credo/check/readability/max_line_length.ex
test/credo/check/readability/max_line_length_test.exs

We had an unimplemented config key for the `LineLength` check, which
I've gone ahead and implemented in this PR. When set to true, it will
ignore any line that consists of only a single string literal, or any
line that is in a heredoc that is longer than the set maximum line
length.
Resolves #122

Implement `ignore_strings` param for `LineLength`

---

.credo.exs
lib/credo/check/readability/missing_typespecs.ex
test/credo/check/readability/missing_typespecs_test.exs

The `MissingTypespecs` readability check compares specs against definitions using the name and the arity. This implementation only checks for specs on `def` and ignores `defp`. Based on a brief survey of core elixir projects it seems rather common to skip typespecs for `defp`, though it could be configurable very easily.
Due to the presence of the function name right in the spec this was _vastly_ easier to work with than `@doc` tags.
This addresses #205

Add missing type specification check for functions

---

lib/credo/check/design/tag_helper.ex
test/credo/check/design/tag_todo_test.exs

I have found a regex bug matching tags: not indented lines were not correctly matched.
I took the opportunity to improve the same regex with more flexible patterns (spaces between # and tag, spaces between tag and the rest of the line).
Thanks.

Fix regex matching tags and improvements.

---

lib/credo/check/runner.ex

Before this, the decision to execute or not the check was based only on the
`base_priority`, but we should read from the user config to decide this kind of
thing.

WIP - Fixing the low priority exclusion

---

lib/credo/cli/command/explain.ex
lib/credo/cli/command/help.ex
lib/credo/cli/command/list.ex
lib/credo/cli/command/suggest.ex

Looking quickly, this has done a fix and I looked around and saw similar approach so hopefully its the right thing to do.
This fixes the following error happening on current master (https://github.com/rrrene/credo/commit/917ea4c416577754d070b0356208d7fa7aa2c5ae)
```shell
mix credo explain --help
Usage: mix credo explain path_line_no_column [options]
Explain the given issue.
Example: $ mix credo explain lib/foo/bar.ex:13:6
General options:
-v, --version       Show version
-h, --help          Show this help
** (FunctionClauseError) no function clause matching in Credo.CLI.to_exit_status/1
lib/credo/cli.ex:157: Credo.CLI.to_exit_status(nil)
lib/credo/cli.ex:61: Credo.CLI.main/1
(mix) lib/mix/task.ex:294: Mix.Task.run_task/3
(mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
(elixir) …
```

fix issue with --help

---

lib/credo/check/readability/specs.ex
lib/credo/check/runner.ex

The current implementation of the type spec check will not properly detect if a typespec is defined against a function which has a guard clause.
Example:
```elixir
def get_foo(bar) when is_map(bar) do
bar[:foo]
end
```
This PR fixes that.

Fix the typespec check when guards are present.

---

lib/credo/cli/filename.ex
test/credo/cli/filename_test.exs

I noticed a while back that there are some functions that were untested
in the CLI part of the app, and I wanted to double back to add some
tests there. I noticed that some doctests had already been written for
`Credo.CLI.Filename`, so I decided to just run with that and turn the
doctests on for that module as part of the test suite.

Add doctests for Credo.CLI.Filename

---

lib/credo/check/readability/trailing_blank_line.ex
lib/credo/check/readability/trailing_white_space.ex

Improve @moduledoc for some readability checks. #257
Since there are no elixir examples that could improve the documentation I decided to and some helping direction to avoid trailing white space or to add new lines at the end of the file

Added more documentation for readability checks

---

.credo.exs
lib/credo/check/warning/map_get_unsafe_pass.ex
test/credo/check/warning/map_get_unsafe_pass_test.exs

Coming from Python this happens every now and then, especially when deserializing. You rarely know (or think!) whether the following function is able to handle `nil` values, and in most cases you run into a runtime at error forcing at minimum a recompile in dev and potentially dumb errors in production.
Mostly the first and consequent `n-1` pipe functions matter, nested expressions are also caught.

Feature: Warn on unsafe `Map.get/2` calls inside pipes

---

.credo.exs
lib/credo/check/readability/semicolons.ex
test/credo/check/readability/semicolons_test.exs

Semicolons are mentioned in the style guide [here](https://github.com/rrrene/elixir-style-guide#semicolon-between-statements), but there weren't any checks.  I tried to fill in the functionality for it since there were already tests.
I'm not super familiar with credo structure, so if I made some mistakes, I'd be happy to try and fix.

Semicolons check

---

lib/credo/check/readability/parentheses_on_zero_arity_defs.ex
test/credo/check/readability/parentheses_on_zero_arity_defs_test.exs

PR related to https://github.com/rrrene/credo/issues/337 
Credo.Check.Readability.ParenthesesOnZeroArityDefs crashes if a macro defines a zero-arity function. 
Credo.Check.Readability.ParenthesesOnZeroArityDefs checks zero arity methods and flags if they have parenthesis.  When generating a zero arity method in a macro we are required to add the parens.  This causes an issue because issues_for_definition/3 sees that args are == 0 but there is no name defined for the method yet (we just have something like ({:unquote, [line: 4], [{:attribute, [line: 4], nil}]}`)... so we blow up.
In theory this check needs to be skipped in this case - as the parens are required to generate the method.  As such I just skip the issue anytime this comes up.

BugFix: Crashes on zero arity function in macro

---

lib/credo/cli/output/ui.ex
test/credo/cli/output/ui_test.exs

The regular expression used in `UI.wrap_at` can break unicode characters into invalid binaries as unicode. Some functions using the result like IO.puts raise exception.
```
iex(1)> Credo.CLI.Output.UI.wrap_at("あ", 1)
[<<227>>, <<129>>, <<130>>]
```
This patch doesn't care about display width of unicode characters.

Set unicode option for regex at UI.wrap_at

---

lib/credo/cli/options.ex

Some point between credo v0.5 and v0.7 the OptionParser started to use `strict` for switches (which would ignore switches that were not defined).
`-C` is an (aliased) switch that allows you to specify a ruleset that you defined on your credo file.
Eg, let's say you have the following `.credo.exs`
```elixir
%{
configs: [
%{
name: "default",
...
},
%{
name: "ci",
...
```
You can execute the checks of the second ruleset by running `mix credo -C ci`. The problem is that with the change from `switches` to `strict`, unfortunately this stopped working, so, before this PR, if you try to run `mix credo -C ci` you would receive the error `Unknown switch: -C`; after this PR it should work as expected

Fix config_name switch

---

lib/credo/sources.ex

Fixed a pattern match that was preventing flycheck from being formatted correctly

---

lib/credo/cli/filename.ex
test/credo/cli/filename_test.exs

Pretty sure this solves #347 .  After making the change, fired up `iex` and ran `Credo.CLI.main([])`. It found 141 source files, and this being windows, I feel like that's an improvement.
I also used this branch as the resolver for another Elixir project on my box, and ran that one with `mix credo` and it found the files.....

turns out in Elixir windows uses '/' instead of '\'

---

lib/credo/check/consistency/space_around_operators.ex
test/credo/check/consistency/space_around_operators_test.exs

From #144, I was still having issues with false positives being reported due to my use of other keywords not listed in the check.

Fix false positives in SpacesAroundOperators

---

lib/credo/execution.ex
lib/credo/execution/task/halt_execution.ex

Ref #376 
This is an addition to the fix in https://github.com/rrrene/credo/commit/a300b110f20df088b862c12ed85a14e51d5e98ad ;)
This fixes an error for commands that does not put anything into the
Execution result "issues" key. E.g. the version command.
Example run without this fix:
```
$ mix credo -v
0.8.0-rc3
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
(elixir) lib/enum.ex:1: Enumerable.impl_for!/1
(elixir) lib/enum.ex:116: Enumerable.reduce/3
(elixir) lib/enum.ex:1776: Enum.map/2
lib/credo/execution/task/halt_execution.ex:20: Credo.Execution.Task.HaltExecution.to_exit_status/1
lib/credo/execution/task/halt_execution.ex:9: Credo.Execution.Task.HaltExecution.call/2
lib/credo/execution/task.ex:30: Credo.Execution.Task.run/3
(mix) lib/mix/task.ex:294: …
```

Default value of result issues

---

README.md

This fixes the ff. error encountered
when "credo" is added to the Mix test alias:
** (Mix) Could not start application credo: Credo.start(:normal, []) returned an error: already started

Exclude Credo from the application runtime list

---

lib/credo/check/consistency/space_around_operators/space_helper.ex
test/credo/check/consistency/space_around_operators_test.exs

When using elixir from master (primarily because of [this](https://github.com/elixir-lang/elixir/pull/6307)), credo crashes with the following error:
<details>
```
15:19:34.077 [error] Task #PID<0.182.0> started from #PID<0.73.0> terminating
** (FunctionClauseError) no function clause matching in Credo.Check.Consistency.SpaceAroundOperators.SpaceHelper.position/1
lib/credo/check/consistency/space_around_operators/space_helper.ex:58: Credo.Check.Consistency.SpaceAroundOperators.SpaceHelper.position({:sigil, {3, 14, 6}, 87, ["\n      name\n      is_active1\n    "], 'a', '('})
lib/credo/check/consistency/space_around_operators/space_helper.ex:46: Credo.Check.Consistency.SpaceAroundOperators.SpaceHelper.no_space_between?/2
lib/credo/check/consistency/space_around_operators/collector.ex:88: …
```

Support sigils in elixir 1.6

---

lib/credo/check.ex

Fix #411
There are about 3 different places a fix for this issue could fit. I
figured this might be the simplest.

Convert missing check params to an empty list

---

lib/credo/check/readability/module_attribute_names.ex
test/credo/check/readability/module_attribute_names_test.exs

Similar scenario as #329, #311, #275 and others. The fix is a carbon copy of how cb0622af407b9bf04fc2d5214020e935d111aca7 handles these cases.

Guard against unquoting attributes on `ModuleAttributeNames`.

---

lib/credo/cli/output/summary.ex
test/credo/cli/output/summary_test.exs

- create an empty umbrella project
- install credo
- run credo
- exception is thrown because there are no source files.
- added test to demonstrate issue
- Added pattern match for empty source_files list to `Credo.CLI.Output.Summary.scope_count/1`

Prevent exception thrown when run against empty umbrella project

---

lib/credo/cli/command/gen.check.ex

Fixes CLI argument parsing for gen.check.

---

lib/credo/execution/task/require_requires.ex

This fixes the loading of the RequireRequires task.
Without the 2nd param, the task is not executed and loading of custom checks fails.

Fix loading of custom checks

---

CONTRIBUTING.md

I was wanting to contribute to this repo. Out of habbit, I just opened up `CONTRIBUTING.md` and I noticed that the markdown was not rendering really well. I saw that there was also a contributing guide in the README (this one rendered properly) so I figured that I would just make them match to avoid confusion.

Clean up contribution guide file to match the one in the readme

---

README.md

* Add "IDE/Editor Integrations" to README, so users can know how to run `mix credo` in their editor of choice.

Add IDE/Editor Integrations

---

README.md

I think the Markdown syntax was backwards for this link, which was pointing to the following (404) location:
https://github.com/rrrene/credo/blob/master/bunt
The updated syntax in this commit should fix the link so it points to the correct location:
https://github.com/rrrene/bunt
/cc @rrrene

Fix Markdown link to bunt in the README

---

lib/credo/check/readability/specs.ex
test/credo/check/readability/specs_test.exs

Noticed that these kinds of specs (ones containing a `with` clause) weren't counting as a spec for the function.

adding a pattern to match @specs containing `with` clauses

---

.credo.exs

You have a lot of warnings now on the test directory, but there are a lot of other warnings elsewhere in the project so i wasn't sure if you wanted to bother to fix it
```
[R] ↓ test/credo/code_test.exs:42:81 Line is too long (max is 80, was 86).
[R] → lib/credo/cli/command/suggest/suggest_output.ex:1:11 Modules should have a @moduledoc tag.
[R] → lib/credo/service/source_file_scopes.ex:1:11 Modules should have a @moduledoc tag.
[R] → lib/credo/cli/command/suggest/output/flycheck.ex:1:11 Modules should have a @moduledoc tag.
[R] ↓ lib/credo/check/warning/io_inspect.ex:23:81 Line is too long (max is 80, was 81).
[R] → lib/credo/execution/task/set_default_command.ex:1:11 Modules should have a @moduledoc tag.
[D] → lib/credo/check/warning/name_redeclaration_by_def.ex:39 Found a TODO tag in a …
```

Include test directory in files that can be limited - fixes #487

---

lib/credo/check/find_lint_attributes.ex

We're using warnings as errors and this warning keeps popping up on Elixir 1.6. This PR is an attempt to suppress the warning.
```
==> credo
Compiling 178 files (.ex)
warning: module attribute @lint was set but never used
lib/credo/check/find_lint_attributes.ex:23
```

Fix warning on unused @lint

---

lib/credo/cli/command/list/list_output.ex
lib/credo/cli/command/suggest/suggest_output.ex
lib/credo/cli/options.ex
test/credo/cli/options_test.exs

Fixes #532
This does 2 things:
1.  It documents the `--min-priority` switch
1.  It adds 5 new possible values to the `--min-priority` (`high`, `medium`, `normal`, `low`, `lower`)
There's one caveat with this PR. It piggies back on the unknown flags handling feature of credo. If the `--min-priority` switch is given a string it can't parse (not one of the values above nor an integer) it'll report that the `--min-priority` switch is unknown. 
This is not great for users but it's consistent with the current behavior of credo. I didn't want to improve the error reporting for non-parsed flags in this PR since it seemed complicated and beyond the scope of the original issue. At least it's not worse than it was before.
Error output from master:
```sh
$ mix credo --min-priority what
Unknown …
```

Add string options for the `--min-priority` switch

---

lib/credo/main_process.ex

Using Credo Version 0.9.2, I did something like:
`mix credo gen.check my_new_custom_check` 
I added the two items it told me to my `.credo.exs` file.  But when I ran credo it said something like:
`Ignoring an undefined check: MyNewCustomCheck`
I dug into the code a bit, and saw it was "validating" before "resolving".  I switched these, and the check worked fine.
Travis passes: https://travis-ci.org/harlantwood/credo/builds/383527554
If I had more time, I would add a failing test as well; perhaps adding to the [smoke test](https://github.com/rrrene/credo/blob/master/test/smoke_test.sh) to run the new custom check and make sure the output contains the expected, or stderr is empty.
Anyway, hope this helps, and doesn't break other things!
Wonderful tool, BTW, so happy to have Credo, and all …

Fix custom tasks by resolving config before validating it

---

.credo.exs
lib/credo/backports/enum.ex
lib/credo/check/readability/alias_order.ex
test/credo/check/readability/alias_order_test.exs

There are already [tests](https://github.com/rrrene/credo/blob/master/test/credo/check/readability/alias_order_test.exs) for this check, waiting to be implemented. They now all pass.
@rrrene This is my first time implementing a check as complex as this one, so I’m looking for feedback if I should have done things differently.
Thank you! 😊

Add new AliasOrder check

---

lib/credo/check/refactor/negated_conditions_with_else.ex
test/credo/check/refactor/negated_conditions_with_else_test.exs

`!` should be used only when the condition is not strictly boolean. In my experience, most of the time `not/2` is the better choice so I defaulted to `not/2` in the examples (but mentioned `!` as well) and fixed the check so that it checks for `not/2` as well.

Report violation for not/2 as well in Refactor.NegatedConditionWithElse

---

.credo.exs
lib/credo/check/refactor/map_into.ex
test/credo/check/refactor/map_into_test.exs

Enum.into/3 only requires one iteration, not two.

Add warning for Enum.map/2 |> Enum.into/2 to prefer Enum.into/3.

---

lib/credo/cli/output/formatter/json.ex
mix.exs
mix.lock

Poison prints deprecation warnings during compilation on Elixir 1.6, and it seems like the general community is largely switching to `jason` over `poison`.  I thought I'd give the conversion a shot in credo, since it's a dependency of many projects and is probably annoying a lot of people with the deprecation warnings.
Things of note:
* `jason` doesn't do pretty printing (yet: https://github.com/michalmuskala/jason/pull/19) so the behavior of `mix credo --format json` changes to printing compact json instead of formatted json. Don't know if this is a concern or not...
* I ran `mix deps.unlock --unused` and it cleaned up the mix.lock file a bunch, since many of those dependencies are not listed anywhere. But it seems like according to the repo badges they're supposed to be there somewhere? …

Switch to Jason for --format json

---

test/credo/check/readability/alias_order_test.exs

This should fix the OTP 18 and 19 compilation errors I introduced with #562 😬

Remove UTF-8 quotation marks from AliasOrder test name

---

lib/credo/check/consistency/space_in_parentheses.ex
lib/credo/check/consistency/space_in_parentheses/collector.ex
test/credo/check/consistency/space_in_parentheses/collector_test.exs
test/credo/check/consistency/space_in_parentheses_test.exs

For issue #176. Adds a new config value for the spaceInParenthesis check to allow for empty enum params to be skipped for consistency. 
`{Credo.Check.Consistency.SpaceInParentheses, allow_empty_enums: true}`

Allow empty enum params

---

lib/credo/check/readability/specs.ex

Correct the documentation on the value of function typespecs. 
Dialyzer analyzes the types used in all expression whether or 
not the related functions have typespecs. Typespecs only 
assist in the analysis.
http://erlang.org/doc/reference_manual/typespec.html
http://erlang.org/doc/man/dialyzer.html

Dialyzer does not ignore functions without typespecs

---

lib/credo/check/readability/specs.ex
test/credo/check/readability/specs_test.exs

The current `Credo.Check.Readability.Specs` check requires that functions which implement a behaviour (`@impl true`) also include a `@spec`, this PR amends the check to exclude those functions from the final report.
Since the existing check doesn't verify the `@spec` is valid I didn't think it necessary for it to verify that `@impl true` is correct (that you included the behaviour and the function is a callback).
@rrrene what are your thoughts?

The Spec check shouldn't require functions that implement behaviours to also have a spec

---

lib/credo/check/refactor/cond_statements.ex

An `if` statement should be recommended when a cond with less than two conditions besides `true` is found.

Clarify what should be used in place of a two condition `cond`.

---

test/credo/check/readability/large_numbers_test.exs
test/credo/exs_loader_test.exs

Example warning:
```
warning: found quoted keyword "dirs_regex" but the quotes are not required. Note that keywords are always atoms, even when quoted, and quotes should only be used to introduce keywords with foreign characters in them
```
Fixes #578

Clean up quoted keyword warnings

---

test/credo/code/parameters_test.exs

Fix "not expr1 in expr2" warnings
Example warning:
```
warning: "not expr1 in expr2" is deprecated. Instead use "expr1 not in expr2" if you require Elixir v1.5+, or "not(expr1 in expr2)" if you have to support earlier Elixir versions
```
Fixes #578

Fix "not expr1 in expr2" warnings

---

lib/credo/cli/output.ex
lib/credo/cli/task/load_and_validate_source_files.ex
lib/credo/source_file.ex
lib/credo/sources.ex
test/credo/source_file_test.exs
test/credo/sources_test.exs
test/test_helper.exs

Credo in our CI environment has been timing out in load_and_validate_source_files.ex. Here is what is displayed:
```
** (exit) exited in: Task.await(%Task{owner: #PID<0.74.0>, pid: #PID<0.406.0>, ref: #Reference<0.2449986766.523763713.102619>}, 5000)
** (EXIT) time out
(elixir) lib/task.ex:501: Task.await/2
(elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
(elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
lib/credo/cli/task/load_and_validate_source_files.ex:11: anonymous fn/1 in Credo.CLI.Task.LoadAndValidateSourceFiles.call/2
(stdlib) timer.erl:166: :timer.tc/1
lib/credo/cli/task/load_and_validate_source_files.ex:9: Credo.CLI.Task.LoadAndValidateSourceFiles.call/2
lib/credo/cli/command/suggest/suggest_command.ex:15: Credo.CLI.Command.Suggest.SuggestCommand.call/2 …
```

handle a timeout when reading files

---

lib/credo/execution/timing.ex
test/test_helper.exs

Running `mix credo` resulted in these warnings:
```
Warnings - please take a look
┃
┃ [W] ↗ Enum.count(issues) == 0 is expensive. Prefer Enum.empty?/1 or list == []
┃       test/test_helper.exs:80:12 #(CredoCheckCase.assert_issue)
┃ [W] ↗ There should be no calls to IO.inspect/1.
┃       lib/credo/execution/timing.ex:11:8 #(Credo.Execution.Timing.inspect)
```
This commit fixes those.
It didn't look like anything in the repo is using `Credo.Execution.Timing.inspect/2`. However, I didn't remove it, just in case any consumers of the library use this function.

Fix Credo warnings

---

lib/credo/check/consistency/space_in_parentheses.ex
lib/credo/check/readability/max_line_length.ex

The `allow_empty_enums` already had a description but it was not inside a `params` array as it seems to be for all the other patterns

Adds missing descriptions for some parameters

---

lib/credo/cli/output.ex
lib/credo/config_builder.ex

Because codeclimate engine read data from stdin, all warnings should go to stderr.
This PR fixes this problem.

Write all warnings to stderr

---

README.md

At Stickler CI we recently shipped support for Elixir via Credo.

Add Stickler CI to list of hosted providers

---

lib/credo/code/token.ex
lib/credo/execution/execution_timing.ex
lib/credo/execution/task/convert_cli_options_to_config.ex

This PR doesn't fix more than a handful of issues, but here's what it does:
* Ignore a readability issue. We want a module name to have underscores when designating an Elixir version.
* Remove deep nesting.
* Allow `IO.inspect/1`, but in a way that `mix format` will not undo. `mix format` added a space before `credo:disable-for-previous-line`, so we needed a different way to ignore that `IO.inspect/1` call.
There are a few readability issues flagged by `mix credo` which involve missing `@moduledoc`s. Would you like me to work on documenting those modules, or would you prefer `@moduledoc false`? Additionally, `mix credo` is flagging a 18 TODOs and one FIXME. Would you like me to convert those to GitHub issues, and remove the TODO and FIXME comments from the codebase? I can do one or both …

Fix a few more issues shown by mix credo

---

lib/credo/check/readability/string_sigils.ex
test/credo/check/readability/string_sigils_test.exs

Currently credo is crashing for the following code:
```elixir
@bad_data %{
"key" => "\xFF"
}
```
```
** (EXIT from #PID<0.91.0>) an exception was raised:
** (FunctionClauseError) no function clause matching in Credo.Check.Readability.StringSigils.too_many_quotes?/3
lib/credo/check/readability/string_sigils.ex:114: Credo.Check.Readability.StringSigils.too_many_quotes?(<<255>>, 0, 3)
lib/credo/check/readability/string_sigils.ex:96: Credo.Check.Readability.StringSigils.issues_for_string_literal/5
lib/credo/check/readability/string_sigils.ex:63: Credo.Check.Readability.StringSigils.traverse/4
(elixir) lib/macro.ex:282: anonymous fn/4 in Macro.do_traverse_args/4
(elixir) lib/enum.ex:1418: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
(elixir) lib/macro.ex:248: Macro.do_traverse/4
(elixir) …
```

Fix StringSigils to not crash with strings containing non-UTF8 characters

---

lib/credo/check/refactor/variable_rebinding.ex
test/credo/check/refactor/variable_rebinding_test.exs

modifies the 'no variable rebinding' to allow for a bang sigil, if the ":allow_bang" option is set.

Bang sigil option

---

lib/credo/check/refactor/abc_size.ex

```
warning: the Collectable protocol is deprecated for non-empty lists. The behaviour of things like Enum.into/2 or "for" comprehensions with an :into option is incorrect when collecting into non-empty lists. If you're collecting into a non-empty keyword list, consider using Keyword.merge/2 instead. If you're collecting into a non-empty list, consider concatenating the two lists with the ++ operator.
(elixir) lib/collectable.ex:83: Collectable.List.into/1
(elixir) lib/enum.ex:1227: Enum.into_protocol/2
lib/credo/check/refactor/abc_size.ex:164: Credo.Check.Refactor.ABCSize.traverse_abc/3
(elixir) lib/macro.ex:286: anonymous fn/4 in Macro.do_traverse_args/4
(elixir) lib/enum.ex:1431: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
```

Fix Elixir warning about Enum.into being ambiguous in ABC Size.

---

lib/credo/cli/output/ui.ex

Issue: #635 
---
Explanation now displays correctly.
* added precondition guard is_nil(line) and doctest for Credo.CLI.Output.UI.truncate

#635-explain on file ending results in FunctionClauseError 

---

lib/credo/check/warning/lazy_logging.ex

As logger is lazy per default on 1.7+ this check is not needed any longer.

Disable logger check on elixir >= 1.7

---

.credo.exs
lib/credo/check/readability/unnecessary_alias_expansion.ex
test/credo/check/readability/unnecessary_alias_expansion_test.exs

I noticed we don’t have a check for this kind of code : 
```elixir
alias Foo.{Bar}
```
Alias expansion with braces is great but I think it affects the code readability when it’s used with a list containing a single item; it should be written : 
```elixir
alias Foo.Bar
```
This new `UnnecessaryAliasExpansion` check makes sure this rule is followed 😄

Add UnnecessaryAliasExpansion check

---

lib/credo/check/refactor/variable_rebinding.ex

The `:allow_bang` option wasn't added to `:params` of the `@explanation` attribute of `Credo.Check.Refactor.VariableRebinding` resulting in the option/parameter not being included in the configuration options:
```
┃    __ CONFIGURATION OPTIONS
┃
┃       You can disable this check by using this tuple
┃
┃         {Credo.Check.Refactor.VariableRebinding, false}
┃
┃       There are no other configuration options.
```
After adding the option the output is as expected:
```
┃    __ CONFIGURATION OPTIONS
┃
┃       To configure this check, use this tuple
┃
┃         {Credo.Check.Refactor.VariableRebinding, <params>}
┃
┃       with <params> being false or any combination of these keywords:
┃
┃         allow_bang:            Variables with a bang suffix will be ignored.
```

add :allow_bang :params to @ explanation of VariableRebinding check

---

.credo.exs
lib/credo/check/readability/multi_alias.ex
test/credo/check/readability/multi_alias_test.exs

Resolves https://github.com/rrrene/credo/issues/641

Add experimental multi-alias expansion warning.

---

lib/credo/code.ex
test/credo/check/design/duplicated_code_test.exs
test/credo/code_test.exs

DuplicatedCode (and other checks which use Credo.Code.remove_metadata)
would fail to detect duplicities whenever there are any external
function calls (aliases in AST) and the duplicities don't happen to be
at exactly the same line numbers. So credo would detect if two modules
are exactly equal, but adding a "# creeedo:disabled-four-that-foul"
comment on top is enough to disable the check, which doesn't seem very
intentional. :-)
This is because Credo.Code.update_metadata doesn't recurse into
{{:., …, …}, …, …}
nodes. Fix this by dropping the hand-crafted implementation and use
Macro.prewalk and Macro.update_meta instead.

Fix DuplicatedCode not matching blocks with external calls

---

.credo.exs
lib/credo/check/consistency/unused_variable_names.ex
lib/credo/check/consistency/unused_variable_names/collector.ex
test/credo/check/consistency/unused_variable_names_test.exs

We want to enforce a single way of naming unused variables, either name them all `_` or give them all meaningful names (eg. `_user`, `_params`, etc.).
What do you think? Do you think this belongs in Credo?
Thank you!

Add Credo.Check.Consistency.UnusedVariableNames

---

lib/credo/check/readability/function_names.ex
test/credo/check/readability/function_names_test.exs

Adds some fixes and improvements to `Readability.FunctionNames`:
- functions defined with parentheses are now verified (previously this check was only verifying a function if it accepts zero args and is defined without parens, i.e. `def some_fun do end`)
- functions with guards (`when` clause) are properly handled
- verifies private macros and custom guards
- generates single report for multiclause functions

Improve Readability.FunctionNames

---

lib/credo/check/readability/parentheses_on_zero_arity_defs.ex
test/credo/check/readability/parentheses_on_zero_arity_defs_test.exs

@rrrene I'm not sure this aligns with the direction you see for Credo. In the Elixir formatter, we went with a clear decision: the formatter is as opinionated as possible, and configuration is the enemy. However Credo seems to be used as a linter more geared towards consistency: for example, look at all the consistency checks which don't enforce a specific style bur rather just a consistent one. For this reason, I think that it might be nice to be able to configure some checks like the one in this PR. I didn't go with any other checks as I want to test the waters first, and get the discussion started on this. Let me know your thoughts! :)

Add an option to enforce parens or not in zero-arity defs

---

lib/credo/check/readability/space_after_commas.ex
lib/credo/code/heredocs.ex
test/credo/code/heredocs_test.exs

`mix credo test.ex` produces outdented heredoc warnings.
test.ex:
```
defmodule Test do
@doc """
a
b
"""
end
```
result:
```
warning: outdented heredoc line. The contents inside the heredoc should be indented at the same level as the closing """. The following is forbidden:
def text do
"""
contents
"""
end
Instead make sure the contents are indented as much as the heredoc closing:
def text do
"""
contents
"""
end
The current heredoc line is indented too little
test.ex:6
```
This PR will fix above problem. Other problems may also be fixed.

Fix outdented heredoc warnings

---

lib/credo/check.ex
lib/credo/issue_meta.ex

A wrong typespec causes dialyzer errors in a client project where custom credo checks are built.

Fix type specification

---

lib/credo/check/readability/parentheses_on_zero_arity_defs.ex

Just a small typo I found in a recent commit by @whatyouhide 🇮🇹

Fixes typo introduced in https://github.com/rrrene/credo/pull/673

---

.credo.exs
lib/credo/check/readability/alias_as.ex
test/credo/check/readability/alias_as_test.exs

resolves #684
The new check is set to low priority and it's included in the list of experimental/controversial checks, which means that by default it will not run, and the user must opt in.

Add check for alias as

---

lib/credo/check/readability/specs.ex
test/credo/check/readability/specs_test.exs

If a callback fun was marked with `@impl BehaviourMod`, `Credo.Check.Readability.Specs` check treated that fun as public.

Fix spec check

---

lib/credo/check/consistency/unused_variable_names/collector.ex
test/credo/check/consistency/unused_variable_names_test.exs

There was a bug in my `unused_variable_name?/1` helper function. I fixed it 😄

Fix name parsing bug in Credo.Check.Consistency.UnusedVariableNames

---

lib/credo/check/readability/function_names.ex
lib/credo/check/readability/module_attribute_names.ex
test/credo/check/readability/function_names_test.exs
test/credo/check/readability/module_attribute_names_test.exs

sometimes it's useful (but, of course, potentially dangerous) to redefine an "@" parameter inside of a using statement.  This form currently gets trapped by credo.  I attempted a strategy of trapping on the outer context being a *defmacro* statement, but this strategy wound up being simpler.  In general, the "@" AST will not be followed by a bracket except in this singular situation.

fix: fixes issue #696

---

lib/credo/check/refactor/module_dependencies.ex
test/credo/check/refactor/module_dependencies_test.exs

Adds umbrella app test directories to default ignore in ModuleDependencies check when in umbrella app.
Fixes #705.

Add regex support and umbrella test path regex to excluded_paths for ModuleDependencies.

---

lib/credo/check/readability/trailing_white_space.ex
test/credo/check/readability/trailing_white_space_test.exs

Fixes the TrailingWhiteSpace check on windows style line endings. 
The current regex `~r/\s+$/` was catching `\r` line endings when it shouldn't catch. 
That commit replace the `\s` with `\h` which is a horizontal whitespace and it's also compliant with PCRE  (Perl Compatible Regular Expressions) that is used by elixir and erlang. 
Fixes #698

Fix TrailingWhiteSpace check on Windows

---

lib/credo/check/readability/multi_alias.ex
test/credo/check/readability/multi_alias_test.exs

The `Credo.Check.Readability.MultiAlias` check was raising an error when trying to parse this code because of the `Bar.Baz` part.
```elixir
alias Foo.{Bar.Baz, Quux}
```
I fixed it and added a test.

Make Credo.Check.Readability.MultiAlias check work with submodule expansion

---

lib/credo/check/readability/alias_as.ex
test/credo/check/readability/alias_as_test.exs

Fix crash in AliasAs check when `__MODULE__` is aliased. Fixes #710.

Fix crash in AliasAs check when __MODULE__ is aliased. Fixes #710.

---

lib/credo/check/refactor/pipe_chain_start.ex
test/credo/check/refactor/pipe_chain_start_test.exs

Fixed logic issue with PipeChainStart when excluding `:atom` and using a `nil`. See #712.

Fix logic issue with PipeChainStart, excluding :atoms, and nil. Fixes #712

---

.credo.exs

This improves the default includes for umbrella apps. For monolith apps, we were targeting lib, src, test, and web, and excluding folders like assets, but umbrellas were targeted with `apps/` which included all the folders like assets in those sub-apps. The new version targets the lib, src, test, and web folders inside `apps/*/`. Fixes #599.
Old config:
```
Analysis took 121.5 seconds (5.8s to load, 115.6s running 61 checks)
```
New config:
```
Analysis took 113.7 seconds (1.1s to load, 112.6s running 61 checks)
```

Improve default includes for umbrella apps. Fixes #559.

---

.credo.exs
lib/credo/config_builder.ex
lib/credo/config_file.ex
lib/credo/execution.ex
lib/credo/sources.ex

This adds a `parse_timeout` flag to the config, which is passed to `Task.yield_many`. It defaults to the existing 5,000ms `yield_many` default timeout.  Fixes #656.

Add parse_timeout to configure timeout parsing files. Fixes #656.

---

lib/credo/check.ex
lib/credo/code/module.ex
lib/credo/code/scope.ex
test/credo/check_test.exs
test/credo/code/scope_test.exs

Fixes #702
You can try this by setting the Credo dep to
```elixir
{:credo, github: "rrrene/credo", branch: "fix-speed-pitfall-on-scope-names"}
```

Fix speed pitfall on Scope.name/2

---

.credo.exs
lib/credo/check/warning/mix_env.ex
test/credo/check/warning/mix_env_test.exs

Add Credo.Check.Warning.MixEnv. Warns on Mix.env usage in app code.

---

lib/credo/check.ex
lib/credo/code.ex
test/credo/check/readability/alias_order_test.exs

The alias and the references to this module no longer make sense since the module was removed in v1.0.0

Remove old CodeHelper references which was removed in v1.0.0

---

lib/credo/check.ex
lib/credo/check/readability/large_numbers.ex
lib/credo/check/readability/parentheses_in_condition.ex
lib/credo/cli/command.ex
lib/credo/execution.ex
lib/credo/execution/task.ex
lib/credo/execution/task/validate_options.ex
lib/credo/issue.ex

Brings dialyzer warnings from 34 down to 1 (which will remain as long as Elixir 1.5 is supported)

Cleaned up dialyzer issues. Unused/unreachable code and incorrect types.

---

lib/credo/check/consistency/line_endings.ex
lib/credo/check/consistency/line_endings/collector.ex

Include first offending line number in each file for the line ending check. Probably will always be line 1 but we should report it anyway for consistent reports. Fixes #253.

Include line number in line ending check. Fixes #253.

---

lib/credo/code/interpolation_helper.ex
test/credo/check/readability/string_sigils_test.exs
test/credo/code/interpolation_helper_test.exs

This PR fixes #729. This was a fun one to track down. When we pass code into `:elixir_tokenizer` to identify the token locations, we first convert the string to a charlist:
https://github.com/rrrene/credo/blob/d77eab696f7a7e485ba6ef3c1a7cc41ccd834fba/lib/credo/code.ex#L132-L134
This results in column numbers consistent with the charlist indexes of the characters. For the unicode character in question (🇿🇼), it translates to two values:
```elixir
iex(1)> String.to_charlist("🇿🇼")
[127487, 127484]
```
This means that when the `:elixir_tokenizer` identifies the `#` token in this string:
```elixir
source = ~S"""
"🇿🇼 #{String.upcase(env)}"
"""
```
it identifies it at the 5th column in the output, which is correct because it is the 5th item in the charlist:
```elixir
{:bin_string, {1, 1, nil},
[ …
```

Fix issue with interpolation of strings vs charlists. Fixes #729.

---

lib/credo/check/warning/unsafe_to_atom.ex
test/credo/check/warning/unsafe_to_atom_test.exs

This PR improves the UnsafeToAtom check to recognize and warn about the use of `keys: :atoms` in `Jason.decode` and `Jason.decode!`.
Jason.decode and Jason.decode! take a `:keys` opt which allows you to choose what type of keys your maps are decoded with. Passing `keys: :atoms` will use the unsafe `String.to_atom` under the hood. Passing `keys: :atoms!` will use the safe `String.to_existing_atom`.

Improve UnsafeToAtom to recognize Jason.decode using keys: :atoms

---

lib/credo/check/refactor/abc_size.ex
test/credo/check/refactor/abc_size_test.exs

Ignore Ecto.Query functions in ABCSize when Ecto.Query is imported.
Fixes #561.

Ignore Ecto.Query functions in ABCSize when Ecto.Query is imported. Fixes #561.

---

lib/credo/sources.ex

There was a bug in here when using plugins that the `parse_timeout` was
`nil`, and then when I tried to use it with `--config-name` it crashed.
Here's what that crash looked like:
```
mix credo --files-included lib/sketchql/subscriptions/sync_schedules.ex --files-included lib/sketchql/subscriptions/stripe/api/client.ex --config-name new_files
** (FunctionClauseError) no function clause matching in Task.yield_many/2
The following arguments were given to Task.yield_many/2:
[%Task{owner: #PID<0.93.0>, pid: #PID<0.116.0>, ref: #Reference<0.323361820.2247360518.21450>}, %Task{owner: #PID<0.93.0>, pid: #PID<0.117.0>, ref: #Reference<0.323361820.2247360518.21451>}]
nil
Attempted function clauses (showing 1 out of 1):
def yield_many(tasks, timeout) when timeout == :infinity or is_integer(timeout) …
```

Fix bug with `nil` parse_timeout

---

.credo.exs

The comment suggests that this should already be a default. Let's make it so.

Enable by default `UnnecessaryAliasExpansion`

---

lib/credo/service/ets_table_helper.ex

Should close #752 
It seems like this sort of solution was intended in the first place: the ets tables are created with `[:named_table, read_concurrency: true]` as options, but the reads are currently serialized through a GenServer the same as the writes are. I can't think of a situation where this would break any credo logic, but at the same time, I don't know the codebase too well.
I checked on the CI mentioned in the original issue and both this PR and it does fix our issue.
The initial workaround of https://github.com/surgeventures/credo/commit/7a4c0abcb921fc3e3558c9d0a8afdbb5d33bc918 works as well, but just increasing GenServer.call timeouts doesn't seem like the right thing to do or like it's a robust solution.
I made the branch off of the `v1.2.2` tag so that we can use the fix …

Enable concurrent reads from ETS services, stop GenServer.call timeouts

---

.credo.exs
lib/credo/check/warning/leaky_environment.ex
lib/credo/check/warning/unsafe_exec.ex
test/credo/check/warning/leaky_environment_test.exs
test/credo/check/warning/unsafe_exec_test.exs

Based on the [Spawning external executables](https://erlef.github.io/security-wg/secure_coding_and_deployment_hardening/external_executables) chapter of the [EEF Security WG Secure Coding and Deployment Hardening Guidelines](https://erlef.github.io/security-wg/secure_coding_and_deployment_hardening/).

Spawning external executables

---

README.md

Add SourceLevel to `README` in `Automated Code Review section`, I've followed alphabetical sort order, if you prefer to add to the end of the list, please let me know :)
We're now supporting the latest patch version for each minor version >= 1.0, [see more details in Credo page in our docs](https://docs.sourcelevel.io/engines/credo/).
Feel free to also check out [engine source code](https://github.com/sourcelevel/engine-credo), that runs Credo.
Thank you for the great tool! :heart:

Add SourceLevel to Automated Code Review section

---

test/test_on_projects.sh

@Plataformatec Elixir OSS projects were moved to @dashbitco namespace.
Reference in [Elixir Forum](https://elixirforum.com/t/jose-valim-announces-his-new-elixir-consultancy-dashbit/28414)

Update Mox repo URL in Community Projects script

---

lib/credo/code/interpolation_helper.ex

`mix format` wanted to add a newline above the commented out IO.inspect, so I removed it instead.
This brings master in line with `mix format`.

Removed commented out IO.inspect

---

lib/credo/check/warning/unsafe_to_atom.ex
test/credo/check/warning/unsafe_to_atom_test.exs

Module attributes are determined at compile time, so are safe to use without fear of overloading the runtime atom table. This PR ignores module attributes for the UnsafeToAtom check.
Fixes #749

Ignore module attributes in UnsafeToAtom

---

lib/credo/check/readability/strict_module_layout.ex
lib/credo/code/module.ex
test/credo/check/readability/strict_module_layout_test.exs
test/credo/code/module_test.exs

This PR brings in a few minor changes/additions to the `StrictModuleLayout` check. These additions are motivated by the real usage in the project of my client (which is where the original implementation of this check was done).
Note that these changes weren't discussed in any issue so far. However, to better understand the issues, I experimented with a fix, and so I ended up with the solution here, and then I figured I may as well submit it :-) That said, I'm not insisting on these changes, and so if you have some other ideas feel free to propose them.
Anyway, here are the changes:
1. Callback macros and callback functions are bundled under the same key `callback_impl`. In other words, with this change we can't enforce that e.g. callback macros must preceed callback functions. The reason …

Improve strict module layout

---

lib/credo/cli/output/summary.ex

Adds note to end of execution noting the `mix credo explain` feature. Only appears when at least one issue is found. Fixes #751.

Add note to end of execution noting `mix credo explain`

---

.credo.exs
lib/credo/check/readability/separate_alias_import_require_use.ex
test/credo/check/readability/separate_alias_import_require_use_test.exs

Adds check to ensure aliases and requires are together in a file.
For example:
```
defmodule Foo do
require Logger
alias Foo.Bar
alias Foo.Baz
require Integer
...
end
```
should be changed to:
```
defmodule Foo do
require Integer
require Logger
alias Foo.Bar
alias Foo.Baz
```
Will fail check if aliases appear on non-consecutive lines within a file, or if requires do likewise.
Ignores code in quotes to allow separate aliases/requires in things like `__using__`.
Accepts multiline multi-alias including surrounding bracket line and newline, and an alias-as that wraps including surrounding newlines.

Add check to ensure aliases and requires are together in a file.

---

lib/credo/check/refactor/variable_rebinding.ex

This was incorrectly surfaced as a warning in an app I work on after upgrading to `v1.4.0`:
$ mix credo
** (config) Credo.Check.Refactor.VariableRebinding: unknown param `allow_bang`.

Add explicit default to Refactor.VariableRebinding check's allow_bang option

---

lib/credo/check/warning/expensive_empty_enum_check.ex
test/credo/check/warning/expensive_empty_enum_check_test.exs

At the moment, credo warns on 
```elixir
length(some_list) == 0
```
After this change, it will also warn on
```elixir
length(some_list) === 0
```

Check for `===` as well as `==` in empty enum check

---

lib/credo/priority.ex

On a larger test file from a real world project (3600 LOC) this reduces the credo check time from what seems like an infinity (I didn't have the patience to let it finish) to 4.7 seconds.
I feel there's some more room for improvements, but this is already a solid gain, while the change is simple enough, so I'm submitting it now. 
Time-permitting I might analyze perf further, but I can't commit. I advise opening up an ongoing issue for this, and establishing some benchmarks, especially for situations when the input file is large, and when there are a lot of issues.
My impression (based on a very shallow walk through a small part of the code) is that credo might not handle such scenarios quite well. I've see some `++` appends performed during traversals, and random-access writes performed …

Improve performance

---

lib/credo/code/module.ex
test/credo/code/module_test.exs

In the previous version, module part analysis would treat multiclauses as distinct functions. That cause problems with the `StrictModuleLayout`.
For example:
```elixir
@impl
def handle_call(...), do:
def handle_call(...), do:
```
The second clause would be incorrectly interpreted as a public function.

Correctly deduplicate multiclauses

---

lib/credo/config_builder.ex

- private fn get_config_file/2 in Credo.ConfigBuilder created the
var `filename` for the expanded path of `config_file` but was not
used and resulted in a warning.

use created expanded filename path

---

lib/credo/check/consistency/space_around_operators.ex
test/credo/check/consistency/space_around_operators_test.exs

The Elixir formatter always removes spaces around the asterisk in
typespecs for binaries by default. Credo shouldn't conflict with the
default Elixir formatter settings, but it raises an issue if the rest of
the file is using spaces around operators.
This PR adds handling of this corner case.

fix Elixir formatter asterisk spacing conflict

---

lib/credo/check/readability/specs.ex
test/credo/check/readability/specs_test.exs

Fixes a bug in `Credo.Check.Readability.Specs`, where a parensless definition (i.e. `def foo do ... end`) was not accounted for.

Properly handle lack of parens in spec check

---

README.md

Emacs has support for credo with the flycheck plugin
https://www.flycheck.org/en/latest/languages.html#elixir

Add Emacs as a supported editor

---

README.md

Closes https://github.com/rrrene/credo/issues/786
Analogous to https://github.com/phoenixframework/phoenix_live_view/pull/1012

add Erlang/OTP 20+ requirement to README

---

README.md

💁 It's useful to be able to click through to the CI build results from documentation.

Docs: add link to CI results

---

lib/credo/cli/command/suggest/output/default.ex

For a number of the checks, it is not clear which specific check you are dealing with when reading through the output in Credo. I have a few times had to copy the error message, then search for it in credo source to figure out which one it is. This PR simply notes the name of the check in parenthesis after the message.
Example:

Add name of check to message when printing issues

---

guides/custom_checks/adding_checks.md

Fixes the link from https://hexdocs.pm/credo/testing.html to https://hexdocs.pm/credo/testing_checks.html in https://hexdocs.pm/credo/adding_checks.html page.

Fixes the link for testing_checks HTML file

---

lib/credo/config_builder.ex

this commit changes the order of the `add_switch_` functions for `strict` and `min_priority`. 
As `add_switch_strict` overwrites in `Execution.set_strict`the min_priority value, it needs to be before the `add_switch_min_priorty`.
See https://github.com/rrrene/credo/blob/master/lib/credo/execution.ex#L298
the last time the order has been changed was with this commit:
https://github.com/rrrene/credo/commit/9d7b62e90b85fc07820ed0c81c371d9c48b0f1c1
Fixes https://github.com/rrrene/credo/issues/777

add min_priority after strict to avoid overwrites

---

lib/credo/code/strings.ex
test/credo/code/strings_test.exs

There was a bug where a charlist before a string would cause the `replace_with_spaces` function to skip the rest of the line.
fixes #809

Fix `Strings.replace_with_spaces` with charlist

---

lib/credo/check/readability/function_names.ex

`<` was missing from the non-special-form-operators list.

adds in missing < operator from this check

---

lib/credo/check/warning/expensive_empty_enum_check.ex
test/credo/check/warning/expensive_empty_enum_check_test.exs

Fix #824
In cases where a local variable called `length` was checked for zero value, credo incorrectly assumed this to be a call to Kernel.length/1 and showed a warning that this was an expensive operation.
This is fixed by making sure pattern match checks length's AST for a single parameter at the last item in the tuple, meeting Kernel.length/1's AST.
This also removes warnings from length function calls with more than a single parameter.
I'm not sure this is desired, but since a length/2+ function can be anything other than checking the size of an enumerable and the suggestion might not be valid, I think it is only fair we don't warn people creating and using a function like that.
Please LMK if you think I should add a test for this scenario or if we should keep warning for length/2+ as …

Fix ExpensiveEmptyEnumCheck when length is a var

---

README.md

The great [VS Code extension](https://github.com/iampeterbanjo/vscode-elixir-linter) of @peterbanjo is no longer maintainted. 😢 
I went ahead and built a new extension 👋🏼 
This PR includes a new VS Code extension for Credo and notifies newcomers about the fact that the extension 'ElixirLinter' is no longer maintained.

Show alternative VS Code extension

---

guides/introduction/exit_statuses.md
lib/credo/execution/task/convert_cli_options_to_config.ex

As reported in #831 when `Credo` fails to load the config file the exit status is `0` (success). This behavior generates a false positive on CI pipelines.
This PR adds a status code `128` when config load fails.
Obs. I didn't find an appropriate test file to add a spec for this new behavior.

Exit with error status when load config fail

---

lib/credo/cli/command/diff/diff_command.ex

This PR fixes `git_present?` for systems that don't have git.
On a system without git available, the previous implementation raises an ErlangError:
```
** (ErlangError) Erlang error: :enoent
(elixir 1.11.2) lib/system.ex:815: System.cmd("git", ["--help"], [])
```
This is solved by rescuing the error.

Fix Git check for systems without git

---

lib/credo/check/readability/specs.ex
test/credo/check/readability/specs_test.exs

I like writing specs for my private functions! Adding an option to enable checking on private functions. Its disabled by default.
To enable:
```elixir
{Credo.Check.Readability.Specs, [include_defp: true]}
```
Added tests for asserting and refuting errors

Adding support for spec checks on private functions

---

.credo.exs
README.md
lib/credo/check/warning/spec_with_struct.ex
test/credo/check/warning/spec_with_struct_test.exs

I was recently working on a project that would recompile ~70 files each time it was recompiled.  I did some digging and figured out that it was a result of using structs eg `%SomeStruct{}` in specs. Switching them out to `SomeStruct.t()` (and making that type) cut down on the modules that would be recompiled each time. Structs create compile-time dependencies and this will warn about structs being used in specs.
I'm happy to turn this off by default or tag it as experimental :)
Thanks for the wonderful library!

Add check for specs containing structs to cut down on compile-time dependencies

---

lib/credo/check.ex

There seems to be support for this option (it's even added by default in the generated custom check), but using Credo.Check will fail as it's not in the list op valid options.

Add :exit_status to the list of valid options

---

.credo.exs
lib/credo/check/design/skip_test_without_comment.ex
test/credo/check/design/skip_without_comment_test.exs

"temporarily" skipped tests can become permanent fixtures in a codebase because the reason for the skip can be forgotten. Ideally skips should not be long-lived, so if you do have to skip a test, you should document why it is being skipped so the skip can be cleared as soon as possible. This check warns if there is not a comment on the line preceding the skip.

Add SkipTestWithoutComment check to warn if no comment precedes `@tag :skip` in a test

---

guides/custom_checks/testing_checks.md

The documentation has an example of validating a property of a list of issues with `assert_issue`.
The anonymous function for `assert_issue` only receives a single issue, I think this example was supposed to use `assert_issues`, which takes a list of issues, instead.

Update example of checking properties of issue list to assert_issues

---

lib/credo/check/refactor/cyclomatic_complexity.ex
test/credo/check/refactor/cyclomatic_complexity_test.exs

Hello credo team! 💜
With this change, credo allows the user to ignore guards when calculating functions CC.
When you have public functions receiving and validating a complex input, pattern matching on head, adding guards can very often exhaust easily the CC calculation, leaving no room for the body.
So I thought this could be a setting on this check, for the projects that want to use guards feature more freely on the function head, but still would like to have max complexity strict for the function body. You think that makes sense?
Thanks!

Allow ignoring guards in CyclomaticComplexity calculation

---

lib/credo/check/readability/predicate_function_names.ex
lib/credo/check/refactor/cyclomatic_complexity.ex
test/credo/check/readability/predicate_function_names_test.exs
test/credo/check/refactor/cyclomatic_complexity_test.exs

The contents of these PRs somehow broke the test suite, i.e.
mix test
times out during random integration tests.
It is unclear at this point, what caused this:
1. Reverting only #867 *or* #869 did not fix it.
2. Reverting only the changes introduced in test/ or lib/ by those PRs did not fix it.

Revert #867 and #869

---

lib/credo/cli/command/diff/task/get_git_diff.ex
lib/credo/cli/output/shell.ex

Rename all instances of 'supress_output' to 'suppress_output'.
Fixes #879

Fix 'supress_output' typo

---

lib/credo/check/design/tag_helper.ex

Trims also tagged strings found in `docs`.

Trim string in TagHelper

---

lib/credo/check/design/alias_usage.ex
test/credo/check/design/alias_usage_test.exs

Currently this check runs on all modules, however, sometimes it's useful
to only run it on a subset of modules. For example, one might want to
only include modules with project top-level module
`ProjectModule.<Module>`.
This was originally proposed in https://github.com/rrrene/credo-proposals/issues/2

Allow to select only required modules for AliasUsage check

---

lib/credo/check/readability/single_pipe.ex
test/credo/check/readability/single_pipe_test.exs

This is based on proposal-65 at https://github.com/rrrene/credo-proposals/issues/65
First time contributor to the repository, and I'm not really sure on what the conventions are, so any criticism is more than welcome.

Add configuration option to SinglePipe, to ignore 0-arity functions

---

lib/credo/check/warning/expensive_empty_enum_check.ex
test/credo/check/warning/expensive_empty_enum_check_test.exs

I made the `Enum.count/1-2` pattern more strict so it only matches the `/1` and not the `/2`. For reference here is the documentation: https://hexdocs.pm/elixir/Enum.html#count/2. I took that example code in the tests :)
Adding this case was a breeze. Thanks for making it so easy 😄

Enum.count/2 needs to execute condition, the alternatives do not apply

---

lib/credo/cli/output.ex
lib/credo/priority.ex
test/credo/cli/output/output_test.exs
test/credo/priority_test.exs

There is an issue with the priority mappings when running `mix explain rule`
I added doctests
```bash
spencercarlson$ mix test test/credo/cli/output/output_test.exs
Excluding tags: [to_be_implemented: true]
........
Finished in 0.04 seconds
8 doctests, 0 failures
```

fixed mix credo explain priority and arrow

---

.github/workflows/ci-workflow.yml
.github/workflows/compatibility-canary-smoke-tests.yml
.github/workflows/compatibility-elixir.yml
.github/workflows/compatibility-phoenix.yml
lib/credo/code/interpolation_helper.ex

Also updated Erlang 22.2 -> 22.3, Elixir 1.11.2 -> 1.11.4 and made Erlang 23 explicitly 23.3.
Removed a unused term that was warning on Elixir 1.11.4 and OTP 24.
Disables fail-fast for the compatibility CI tests.
Update the canary smoke tests to use the latest OTP 24.0 and Elixir 1.12.2

Add Elixir 1.12.2 and Erlang 24.0 to the CI matrix

---

.credo.exs
lib/credo/check/refactor/io_puts.ex
test/credo/check/refactor/io_puts_test.exs

I was surprised to see that there was a check for `IO.inspect` and not for `IO.puts`, so I added one. It's almost an exact copy of the `IO.inspect` code.
Btw, thanks for your hard work on Credo! Saved me a bunch of time over the years.

Add a check for IO.puts

---

lib/credo/check/readability/multi_alias.ex

The statement "Avoid multi aliases ... consider removing" confused several members of our team, who assumed that this was indicating that a single module was aliased multiple times.
With this PR, I am trying to clarify what the actual issue is and how best to remediate it.

Clarify verbiage for Readability.MultiAlias check

---

CHANGELOG.md

Low hanging fruit: In the changelog, the link for `Credo.Check.Readability.MaxLineLength.html#module-max_length` is broken 😢

Fix changelog max_length broken link

---

lib/credo/check/refactor/abc_size.ex
lib/credo/check/warning/application_config_in_module_attribute.ex
lib/credo/check/warning/forbidden_module.ex
lib/credo/cli/output/ui.ex
lib/credo/code.ex
lib/credo/code/interpolation_helper.ex
test/credo/check/readability/single_pipe_test.exs
test/credo/check/refactor/redundant_with_clause_result_test.exs

Related to https://github.com/rrrene/credo/issues/893. 
This still doesn't fix interpolation, which is broken.

fix: handle errors from tokenizer on elixir 1.13+

---

lib/credo/check/refactor/unless_with_else.ex

Hello, I am a maintainer of the Elixir track on [Exercism](https://exercism.org), and one of the tool in the track I work on is a [code analyzer](https://github.com/exercism/elixir-analyzer). Credo has inspired us a lot for that project, so many thanks to you.
Long story short, we were working on a check for `unless` with `else`, we looked at the message you provided, and found a typo in it.

Grammar fix

---

lib/credo/check/consistency/unused_variable_names/collector.ex
test/credo/check/consistency/unused_variable_names_test.exs

Hello credo team! 👋 
First of all thankyou for this great package! 
When enabling`UnusedVariableNames` rule I noticed that it doesnt detect the unused variable when using guard due to different structure of the ast
```elixir
[
{:_, [line: 3, column: 13], nil},
{:_, [line: 3, column: 16], nil},
{:_, [line: 3, column: 19], nil}
]
[
{:bar, [line: 3, column: 9],
[
{:_, [line: 3, column: 13], nil},
{:x2, [line: 3, column: 16], nil},
{:_x3, [line: 3, column: 20], nil}
]},
{:is_nil, [line: 3, column: 30], [{:x2, [line: 3, column: 37], nil}]}
]
```
To give concrete example, if the function is using guard with unused variable, the unused variable will not be detected by the collector
```elixir
Credo.Check.Consistency.UnusedVariableNames, [force: :anonymous]
def bar(_, x2, _x3) when is_nil(x2) do …
```

FIX: detect unused variable when using guards

---

lib/credo/code/sigils.ex
test/credo/check/config_comment_finder_test.exs
test/credo/code/sigils_test.exs

This fixes a bug that presents itself with the following behavior:
The existence of a heredoc-style sigil (with `"""` delimiters) causes credo to ignore all config comments appearing after the sigil.
This affects code written with any library that defines a sigil and is commonly used in heredoc style, such as [LiveView](https://hex.pm/packages/phoenix_live_view) (with HEEx `~H` sigils) and [Surface](https://hex.pm/packages/surface) (with `~F` sigils).
Internally, there is a mechanism that replaces the contents of sigils with spaces in order to avoid misinterpreting their contents as config comments. This mechanism was unable to properly detect the end of the sigil. As a result, code like this
```elixir
defmodule MyModule do
def render do
~F"""
"""
end
def foo, do: :ok
end
```
would be …

Detect end of ~A""" style sigils correctly when searching for config comments

---

lib/credo/check/warning/io_inspect.ex
test/credo/check/warning/io_inspect_test.exs

As originally proposed in https://github.com/rrrene/credo-proposals/issues/72, this PR extends the `Credo.Check.Warning.IoInspect` check to also consider calls to `Elixir.IO.inspect` under the same rule, as the two calls are functionally the same.

Extend Credo.Check.Warning.IoInspect to consider Elixir.IO.inspect in addition to IO.inspect

---

lib/credo/execution/task/initialize_plugins.ex

Closes #928 replacing `function_exported?/3` by `Code.ensure_loaded?/1` as well as indicated in documentation:
> Note that this function does not load the module in case it is not loaded. Check Code.ensure_loaded/1 for more information.
[https://hexdocs.pm/elixir/Kernel.html#function_exported?/3](https://hexdocs.pm/elixir/Kernel.html#function_exported?/3)

Check plugin module loaded fixed

---

lib/credo/check/readability/nested_function_calls.ex
test/credo/check/readability/nested_function_calls_test.exs

This PR adds a check named `Credo.Check.Readability.NestedFunctionCalls` that checks for nested function calls that could be converted to pipelines. I created this check to catch violations of the rule about nested function calls specified in the Christopher Adam's style guide (https://github.com/christopheradams/elixir_style_guide#pipe-operator)
It tries to be smart enough to handle things like access protocol, string interpolation, and function calls with no arguments. See the tests for examples.
Context:
* https://github.com/christopheradams/elixir_style_guide/issues/143#issuecomment-394191496

Add nested function calls check

---

lib/credo/cli/command/suggest/suggest_command.ex

The documentation lists `-i` as an alias for `--ignore`/`--ignore-checks`, however it wasn't specified in the options.

Add alias -i to ignore options

---

lib/credo/code/strings.ex
test/credo/check/readability/space_after_commas_test.exs
test/credo/code/strings_test.exs

Fixes #940 (at least the space after comma warning) for my use-case

fix bug with string literals after custom sigils

---

README.md

I'm seriously impressed with `null-ls` and it's `credo` integration, thought it was worth documenting for others. Thanks!

Add null-ls diagnostic to README

---

lib/credo/check/warning/forbidden_module.ex
test/credo/check/warning/forbidden_module_test.exs

Fixes #946 
Makes the `Credo.Check.Warning.ForbiddenModule` check work when the forbidden module is aliased in a grouped alias like:
```elixir
defmodule CredoSampleModule do
alias CredoSampleModule.{ForbiddenModule}
def some_function, do: ForbiddenModule.another_function()
end
```

Make Credo.Check.Warning.ForbiddenModule work for grouped aliases

---

lib/credo/check/refactor/map_join.ex

The previous explanation appears to have been copied from Credo.Check.Refactor.MapMap.

Update explanation for Credo.Check.Refactor.MapJoin

---

lib/credo/check/refactor/negated_is_nil.ex
test/credo/check/refactor/negated_is_nil_test.exs

Fixes #958
Make `Credo.Check.Refactor.NegatedIsNil` work for multi clause guard like:
```elixir
def foo(%{item_map: item_map, item_type: item_type})
when not is_nil(item_type) and is_map(item_map) do
...
end
```

Make Credo.Check.Refactor.NegatedIsNil work for multi clause guard

---

mix.exs

In current docs it's really hard to navigate between check modules - the names are so long they don't fit the sidebar. This PR adds a `nest_modules_by_prefix` config for `ex_doc` that shortens the names as seen below:

Add module nesting in docs

---

lib/credo/check/readability/large_numbers.ex
test/credo/check/readability/large_numbers_test.exs

More specificity is helpful in the messages. While the old message gives you the correct value for the violation, it did not offer guidance on avoiding the error subsequently. Additionally, given that the `only_greater_than` is user-configurable, teams that change the default would have to go digging to find the threshold.

Includes the 'only_greater_than' value in the LargeNumbers message

---

lib/credo/check/consistency/line_endings/collector.ex
test/credo/check/consistency/line_endings_test.exs

The last line of a file has no line break. So after the splitting into lines the last line of a windows file was always detected as unix because the line never ended with \r.
To fix this do not check the last line of a file.

fix LineEndings check for windows line endings.

---

lib/credo/check/readability/with_single_clause.ex
test/credo/check/readability/with_single_clause_test.exs

Fix #972
As mentioned in the issue discussion, there is no way to know if [unquote_splicing/1](https://hexdocs.pm/elixir/Kernel.SpecialForms.html#unquote_splicing/1) will expand to more than one clause.
I changed `Credo.Check.Readability.WithSingleClause` to never return an error if using `unquote_splicing`, regardless of the amount of `<-` used or `else` branches.

Fix false positive with unquote_splicing

---

lib/credo/check/readability/module_doc.ex

This change will ignore module docs for phoenix live views by default. According to [this code sample](https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/router.ex#L415) live views should end with a `Live` suffix like so `MyApp.ExampleLive`.

Ignore Phoenix.LiveView modules by default

---

lib/credo/check/readability/module_doc.ex

This is a follow up from https://github.com/rrrene/credo/pull/961#issuecomment-1197071958. Sorry for the delay. This should cover modules like `DemoWeb.TestLive` and `DemoWeb.TestLive.Index`.

Update ModuleDoc regex for LiveView

---

guides/introduction/exit_statuses.md

I noticed that we're now supporting elixir 1.14, just saw one remaining doc that still using `use Bitwise`, as per deprecation notice we want to use `import Bitwise` instead of `use Bitwise`

Update docs to use import Bitwise

---

guides/custom_checks/testing_checks.md

The current instructions for testing a custom check do not work if you do not want to add `credo` to your production build.  Adding `:credo` to `extra_applications` causes environments where credo is not included to fail to start.
As an alternative this PR replaces that instruction with an instruction to add `Application.ensure_all_started(:credo)` to the `test_helper.exs` file.  That way credo starts but does not have to be included in all envs.
See https://github.com/rrrene/credo/issues/1003

Application config agnostic testing instructions

---

.credo.exs
lib/credo/check/warning/dbg.ex
test/credo/check/warning/dbg_test.exs

Implements a warning for calls to the dbg/0 or dbg/2 Kernel fns.
I used the IO.inspect check as a reference.

feat: warn on dbg calls

---

.credo.exs
lib/credo/check/readability/one_arity_function_in_pipe.ex
test/credo/check/readability/one_arity_function_in_pipe_test.exs

Some style guides propose:
> Use parentheses for one-arity functions when using the pipe operator (|>)
> ```elixir
> # not preferred
> some_string |> String.downcase |> String.trim
> 
> # preferred
> some_string |> String.downcase() |> String.trim()
> ```
This PR provides a check for that.

Add new check for one-arity functions in pipes

---

.credo.exs
lib/credo/check/readability/pipe_per_line.ex
test/credo/check/readability/pipe_per_line_test.exs

Some style guide proposes:
```elixir
1 |> Integer.to_string() |> String.to_integer()
1
|> Integer.to_string()
|> String.to_integer()
```
This PR provides a check for that.
--
Credits by @bamorim

add new check for pipe per line 

---

.credo.exs
lib/credo/check/refactor/filter_count.ex
test/credo/check/refactor/filter_count_test.exs

This extends Credo such that it looks for use cases for [Enum.count/2](https://hexdocs.pm/elixir/1.14.2/Enum.html#count/2). Alas, I only learned about https://github.com/rrrene/credo-proposals _after_ creating these commits so this PR is 'out of the blue'. 😔 However, I hope that it's not too controversial since the proposed refactoring is much like the one for `Enum.map_join/3`.
Using `Enum.count/2` instead of composing `Enum.filter/2` with `Enum.count/1` is preferable since
1. `Enum.count/2` requires just a single pass, so it's a little more efficient
2. It's less code
The check ID `EX4030` was determined by checking the other IDs and simply picking the next larger value; the largest check ID for refactoring checks appears to be `EX4029`, so that's how I ended up with `EX4030`. 😊 
The …

Add refactoring check suggesting to use Enum.count/2 if applicable

---

lib/credo/check/readability/module_doc.ex

Phoenix 1.7 introduces [new approach to defining views](https://www.phoenixframework.org/blog/phoenix-1.7-released) where the module name is suffixed with the format like so:
```
defmodule AppWeb.PageHTML do
use AppWeb, :html
embed_templates "page_html/*"
end
defmodule AppWeb.PostJSON do
end
```
The PR updates the defaults for the `ModuleDoc` check.

Update `ModuleDoc` defaults for Phoenix 1.7+ views

---

lib/credo/check/readability/function_names.ex

Hi, thank you for credo!
I'm trying to use newly added custom operators `+++` and `---` from Elixir v1.11.0, but `Readability.FunctionName` didn't seem to support it. 
This pull request only add it.

Add custom operators for Readability.FunctionNames

---

lib/credo/check/readability/module_names.ex
test/credo/check/readability/module_names_test.exs

- Adds :ignore param
- :ignore is a list of regexes
- Adds tests for the functionality
Given
ignore: [~r/Sample_Module$/]
Credo.Sample_Module will pass ✅ 
Credo.Another_Module.Sample_Module will fail ❌
Context:
On our project for versioning reasons, we decided to add an API version to a module name, but credo didn't have an option to configure it.
closes https://github.com/rrrene/credo-proposals/issues/83

feat: Add Ignore option for Credo.Check.Readability.ModuleNames

---

lib/credo/code/module.ex
test/credo/code/module_test.exs

In case of a guard the `ast` was not properly traversed and in case of a callback implementation the `@impl` attribute was not propagated to the remaining clauses

properly analyze function with guards

---

lib/credo/check/design/pass_async.ex
test/credo/check/design/pass_async_test.exs

Extracted from an app. We configure this in `.credo.exs` like:
```elixir
{MyApp.Checks.PassAsync, files: %{included: ["**/*_test.exs"]}}
```

New check: PassAsync

---

lib/credo/check/warning/unsafe_to_atom.ex
test/credo/check/warning/unsafe_to_atom_test.exs

Currently, if a call to `String.to_atom/1`, `List.to_atom/1`,
`Module.concat/{1,2}`, `:erlang.list_to_atom/1` and
`:erlang.binary_to_atom/2` is in a pipe (`|>`) chain, it is not
detected by the `UnsafeToAtom` check.
This change alters the prewalk check to unpipe those chains and insert
a phantom argument in the chain to make the arity "correct" and allow
detection.

Check UnsafeToAtom along pipe chains

---

.tool-versions
lib/credo/check/design/alias_usage.ex
test/credo/check/design/alias_usage_test.exs

Related to #956 
I want to check in early to make sure I'm on the right path.
When a module is passed as an argument to a function, it should maybe be aliased?
What I'm actually trying to fix is probably when a module is passed to a macro and not aliased. I may try to update the PR if I'm on the right path.

[956] Add test and maybe a fix for modules passed as arguments

---

lib/credo/check/warning/missed_metadata_key_in_logger_config.ex
test/credo/check/warning/missed_metadata_key_in_logger_config_test.exs

Hello, this is another take on this PR https://github.com/rrrene/credo/pull/1035 which fixes the `metadata: :all` behavior for [MissedMetadataKeyInLoggerConfig](https://github.com/rrrene/credo/blob/master/lib/credo/check/warning/missed_metadata_key_in_logger_config.ex) check.
The issue with the check is that it doesn't properly support the `metadata: :all` configuration. This PR is different from the linked one because it skips running the check entirely if `metadata: :all` is set (since it makes no sense to run it), I've also added a new test that covers the scenario.
Please let me know if it needs to be tweaked before merging.
**What this PR does?**
This pull request prevents credo from crashing when `metadata_keys == :all` and when `MissedMetadataKeyInLoggerConfig` check runs.
**More …

fix logger metadata check when metadata :all set

---

guides/commands/suggest_command.md
guides/configuration/cli_switches.md
lib/credo/cli/command/diff/diff_output.ex
lib/credo/cli/command/info/info_output.ex
lib/credo/cli/command/list/list_output.ex
lib/credo/cli/command/suggest/suggest_output.ex

They weren't updated to add higher and remove medium/lower
I took the valid values from:
https://github.com/axelson/credo/blob/e3f2c21a7a88db54d6256d67997cda6acfe06c08/lib/credo/priority.ex#L15-L21
Without this fix user's may run into this error:
```
$ mix credo suggest --min-priority=medium
** (RuntimeError) Got an invalid priority: :medium
lib/credo/priority.ex:37: Credo.Priority.to_integer/1
lib/credo/cli/options.ex:179: Credo.CLI.Options.patch_switch/2
(elixir 1.14.3) lib/enum.ex:1780: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
lib/credo/cli/options.ex:173: Credo.CLI.Options.patch_switches/1
lib/credo/cli/options.ex:114: Credo.CLI.Options.parse_result/7
lib/credo/execution/task/parse_options.ex:39: Credo.Execution.Task.ParseOptions.call/2
lib/credo/execution/task.ex:133: …
```

Fix docs for priority

---

lib/credo/check/runner.ex

Files coming in via standard input are not on the filesystem, and consulting includes and excludes makes an execution run hundreds of times slower than it should be.
This PR checks to see if the execution is reading from standard input and if so, returns an empty list to bypass the checks.
Fixes #1054

If reading from standard input, do not consult the filesystem

---

mix.lock

This upgrades the `ssl_verify_fun` dependency from 1.1.6 to 1.1.7, fixing builds with Elixir 1.15 which would run into errors like
```
==> ssl_verify_fun
Compiling 7 files (.erl)
src/ssl_verify_fun_cert_helpers.erl:13:14: can't find include lib "public_key/include/public_key.hrl"
%   13| -include_lib("public_key/include/public_key.hrl").
%     |
...
src/ssl_verify_hostname.erl:76:38: record 'OTPCertificate' undefined
%   76|                              Cert :: #'OTPCertificate'{},
%     |                                      ^
could not compile dependency :ssl_verify_fun, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ssl_verify_fun --force", update it with "mix deps.update ssl_verify_fun" or clean it with "mix deps.clean …
```

Fix building with Elixir 1.15

---

lib/credo/check/warning/mix_env.ex
test/credo/check/warning/mix_env_test.exs

Hi! 🖖 
There is a warning getting logged when compiling `Credo.Check.Warning.MixEnv`:
```shell
❯ mix compile lib/credo/check/warning/mix_env.ex
Compiling 1 file (.ex)
warning: function traverse/4 is unused
│
56 │     defp traverse({unquote(op), _, nil} = ast, issues, _issue_meta, _parens?) do
│          ~
│
└─ lib/credo/check/warning/mix_env.ex:56:10: Credo.Check.Warning.MixEnv (module)
```
This pull request fixes it by removing the extra `parens?` argument from the `traverse` function and adds a little test to ensure nothing is broken.

Fixes unused function warning in MixEnv check

---

.github/workflows/ci-workflow.yml
.github/workflows/compatibility-elixir.yml
.github/workflows/compatibility-phoenix.yml
.tool-versions

Commits mostly stand by themselves and should include rational, I can spin off more PRs if wanted but they were _somehow_ related

Upgrade CI (Test against OTP 26, 24.3 instead of 24, 1.16 rc)

---

lib/credo/check/consistency/multi_alias_import_require_use/collector.ex
test/credo/check/consistency/multi_alias_import_require_use_test.exs

Fixes #1023 
When you have files that contain multiple modules this rule will raise a false positive and force a user to disable the rule for the file. These changes solve that, but they _do not_ solve the issue where you have mixed usage in just a single file. We could do that, but the scope was increase quite a bit and most likely isn't super important.

fix: MultiAliasImportRequireUse collection and false positive

---

lib/credo/check/refactor/negated_is_nil.ex
test/credo/check/refactor/negated_is_nil_test.exs

Fixes #1056.
Prior to this, this example test would raise 9 issues:
```elixir
test "regression test for issue list duplication" do
"""
defmodule CredoSampleModule do
def hello(a) when not is_nil(a), do: a
def foo1(x) when is_integer(x), do: x
def foo2(x) when is_integer(x), do: x
def foo3(x) when is_integer(x), do: x
end
"""
|> to_source_file()
|> run_check(@described_check)
|> assert_issue()
end
```

fix: NegatedIsNil memory leak

---

lib/credo/application.ex
lib/credo/check.ex
lib/credo/service/source_file_scope_priorities.ex

Currently, every call to `format_issue` recalculates the scope priorities. This significantly hurts performance when many issues are reported. 
This change adds another ETS table (following the present cache design) to lazily cache these prios. On a large project with almost 7000 issues, this brings the running time of `mix credo` from 26 seconds to 10 seconds. 
Obviously there's more room for improvement, but I think this gain is already significant, and the change is simple enough to be merged on its own. Time-permitting I'll investigate further, but I can't make any promises.

Cache scope priorities

---

lib/credo/check/readability/strict_module_layout.ex
lib/credo/code/module.ex
test/credo/check/readability/strict_module_layout_test.exs
test/credo/code/module_test.exs

A lot of libraries define custom attributes and DSLs that adjust code in the next function. This PR allows users to ignore specific attributes from the `Credo.Check.Readability.StrictModuleLayout` check. Documentation and tests included.
Examples:
- `@decorate` [library](https://hexdocs.pm/decorator/readme.html)
- `@trace` [libraries](https://hexdocs.pm/new_relic_agent/NewRelic.Tracer.html#content)

feat: allow ignoring module attributes in Credo.Check.Readability.StrictModuleLayout

---

lib/credo/check/readability/alias_order.ex
test/credo/check/readability/alias_order_test.exs

I have an app where this is the case. Vim's `sort` and recode's alias order say that this test should be correct but credo disagrees.
I took a stab at trying to fix this but I only had a limited time and I couldn't get it work work with existing tests. I'll open an issue and link theses. Let me know if there's anything else I can do.

Add test for case-sensitive alias ordering

---

lib/credo/check/consistency/space_around_operators.ex
lib/credo/cli/command/diff/diff_summary.ex
lib/credo/cli/output/first_run_hint.ex
lib/credo/cli/output/summary.ex
test/credo/config_file_test.exs

Changed Enum.filter/2 |> Enum.count/1 to Enum.count/2 as recommended by credo.

refactoring opp: [F] ↗  is more efficient than

---

lib/credo/check/readability/predicate_function_names.ex

Before:
https://hexdocs.pm/credo/Credo.Check.Readability.PredicateFunctionNames.html
After:

Fix markdown in PredicateFunctionNames

---

lib/credo/check.ex
lib/credo/check/consistency/collector.ex
lib/credo/check/design/duplicated_code.ex
lib/credo/check/runner.ex
lib/credo/cli/output/summary.ex
lib/credo/sources.ex

Similar to #1077, optimizes the use of streams of tasks in credo in a few more places.
in addition to swapping `Enum.map(&Task.async(...))` -> `Task.async_stream`, this pr also removes ordering from the streams (where possible) for more slight performance gains (h/t @milmazz)

Improve usage of Tasks

---

lib/credo/check/readability/variable_names.ex
test/credo/check/readability/variable_names_test.exs

This clause helped a test pass, but the test is made of code that can't compile
```ex
Interactive Elixir (1.15.7) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> defmodule CredoSampleModule do
...(1)>       def some_function(param, p2, p3) do
...(1)>         [someValue + v2 + v3 | {someValue} <- param, v2 <- p2, v3 <- p3]
...(1)>       end
...(1)>     end
error: misplaced operator |/2
```

Remove variable name clause for check that can't compile

---

.credo.exs
lib/credo/check/readability/duplicated_aliases.ex
test/credo/check/readability/duplicated_aliases_test.exs

This PR adds a check for detecting duplicated aliases in files.
These can end up being merged after solving merge conflicts if we have modules that use many aliases and are not that easy to spot. 
Using this check we can check for duplicated alias right in CI and prevent code like this from being merged.
Currently this PR don't target multi-aliases, but I think it would be useful to target it as well. If there's interest let me know and I'll add this

Add duplicated alias check

---

guides/configuration/config_comments.md

"preceding" refers to something before the statement.  The correct word is `following` here.

Fix comment regarding how `credo:disable-for-lines` works

---

lib/credo/check/readability/predicate_function_names.ex
test/credo/check/readability/predicate_function_names_test.exs

- Closes #1108
If any `:def, :defp, :defmacro` is preceded with `:impl`, we ignore.
Code is mostly inspired from the impl of `Specs`

Ignore PredicateFunctionNames when is impl

---

lib/credo/check/readability/function_names.ex
lib/credo/check/warning/dbg.ex
lib/credo/check/warning/io_inspect.ex
test/credo/check/warning/dbg_test.exs
test/credo/check/warning/io_inspect_test.exs

Previously, this was backfilling the column based on analyzing the
source code line, but the column is already available in the AST, so we
instead take it from there.
This allows IDE type tools to accurately create refactor "code actions".

Fix incorrect columns for dbg and IO.inspect

---

lib/credo/check/params.ex
lib/credo/cli/output/formatter/sarif.ex
lib/credo/cli/task/prepare_checks_to_run.ex
lib/credo/cli/task/set_relevant_issues.ex
lib/credo/execution/task/initialize_command.ex
lib/credo/execution/task/parse_options.ex
lib/credo/execution/task/validate_config.ex

1.17 deprecates calling remote functions without parentheses, which
means that calls like `Foo.Bar.run` and `foo = %{bar: Foo}; foo.bar.run`
should instead be formatted like
`Foo.Bar.run()` and `foo = %{bar: Foo}; foo.bar.run()`
This show up as runtime warnings.

Fix deprecation for 1.17

---

lib/credo/check/config_comment.ex
lib/credo/check/consistency/multi_alias_import_require_use/collector.ex
lib/credo/check/warning/unused_function_return_helper.ex
lib/credo/cli/command/diff/task/get_git_diff.ex
lib/credo/cli/command/explain/output/default.ex

In Elixir 1.17-rc.0 we get these warnings:
```elixir
==> credo
Compiling 253 files (.ex)
warning: x..y inside match is deprecated, you must always match on the step: x..y//var or x..y//_ if you want to ignore it
(credo 1.7.4) lib/credo/backports.ex:4: Credo.Backports.Enum.slice/2
warning: x..y inside match is deprecated, you must always match on the step: x..y//var or x..y//_ if you want to ignore it
(credo 1.7.4) lib/credo/backports.ex:16: Credo.Backports.String.slice/2
warning: 0..-2 has a default step of -1, please write 0..-2//-1 instead
(credo 1.7.4) lib/credo/cli/command/explain/output/default.ex:272: Credo.CLI.Command.Explain.Output.Default.print_check_explanation/2
warning: 1..-1 has a default step of -1, please write 1..-1//-1 instead
(credo 1.7.4) …
```

Use explicit negative ranges

---

lib/credo/check/design/skip_test_without_comment.ex
lib/credo/check/refactor/pass_async_in_test_cases.ex
lib/credo/check/warning/wrong_test_file_extension.ex

Hello! I ran into an issue where `Credo.Check.Refactor.PassAsyncInTestCases` would not flag issues when running `mix credo` from the root of an umbrella application, but `cd`-ing into `apps/app_web` and running it from there would correctly flag the missing `async` option.
We only have a single `.credo.exs` config at the root and I replicated the issue with the barebones config:
```elixir
%{
configs: [
%{
name: "default",
checks: %{
enabled: [{Credo.Check.Refactor.PassAsyncInTestCases, []}]
}
}
]
}
```
Before this change, inside the `Credo.Sources.find_in_dir` the value for `included_patterns` would compile down to:
```
["/Users/tom/my_umbrella_app/test/**/*_test.exs"]
```
But that would skip everything that was under `my_umbrella_app/apps/**/test`
I see this was intentionally changed in …

Fix the path for included files in umbrella apps

---

lib/credo/check/readability/function_names.ex
test/credo/check/readability/function_names_test.exs

This pull request updates the `Credo.Check.Readability.FunctionNames` module to ignore function names when the sigil is private. It also includes test cases to ensure the expected behavior.

Ignore FunctionNames when sigil is private

---

lib/credo/check/warning/io_inspect.ex
test/credo/check/warning/io_inspect_test.exs

It seems unlikely that an inspect call with a specific file handler passed in would be from a debugging session, so it makes sense to exclude these calls.
Thoughts?

Change to not warn on calls to IO.inspect/3

---

lib/credo/check/refactor/apply.ex
test/credo/check/refactor/apply_test.exs

False positive in Credo.Check.Refactor.Apply

---

lib/credo/check/params.ex
lib/credo/cli/output.ex

Avoids this warning for elixir 1.17+
```
warning: using module.function() notation (with parentheses) to fetch map field :category is deprecated, you must remove the parentheses: map.field
(credo 1.7.7) lib/credo/cli/output.ex:36: Credo.CLI.Output.check_tag/2
(credo 1.7.7) lib/credo/cli/output/formatter/flycheck.ex:26: Credo.CLI.Output.Formatter.Flycheck.to_flycheck/1
(credo 1.7.7) lib/credo/cli/output/formatter/flycheck.ex:12: anonymous fn/1 in Credo.CLI.Output.Formatter.Flycheck.print_issues/1
(elixir 1.17.2) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
(credo 1.7.7) lib/credo/cli/command/suggest/suggest_command.ex:77: Credo.CLI.Command.Suggest.SuggestCommand.PrintResultsAndSummary.call/1
```

Remove deprecated module.function() notation

---

lib/credo/code/parameters.ex
test/credo/code/parameters_test.exs

Hi René,
Counting parameters wasn't working quite right when a function hard a guard clause. I believe this fixes it.
Let me know if you want me to tweak anything or raise an associated issue.
💚

Fixes counting params when a function has a guard

---

lib/credo/check/readability/function_names.ex
test/credo/check/readability/function_names_test.exs

This stops e.g. the following code from showing a readability warning:
```
defmodule CredoTest do
@moduledoc """
An example of the snakecase test failing
"""
def a ** b do
nil
end
end
```

Add ** operator

---

lib/credo/check/params.ex

```
warning: using map.field notation (without parentheses) to invoke function Credo.Check.Refactor.ModuleDependencies.category() is deprecated, you must add parentheses instead: remote.function()
(credo 1.7.9) lib/credo/check/params.ex:74: Credo.Check.Params.category/2
(credo 1.7.9) lib/credo/check.ex:697: Credo.Check.format_issue/3
(credo 1.7.9) lib/credo/check/refactor/module_dependencies.ex:111: Credo.Check.Refactor.ModuleDependencies.issues_for_module/5
(credo 1.7.9) lib/credo/check/refactor/module_dependencies.ex:89: Credo.Check.Refactor.ModuleDependencies.traverse/6
(elixir 1.17.3) lib/macro.ex:599: Macro.traverse/4
```

fix missing parentheses warning in `Credo.Check.Params.category/2`

---

lib/credo/check.ex
test/credo/check_test.exs

Introducing support for a custom `category` option in the `format_issue` function, so we can overwrite the category given by Credo.Check `use` spec.
This allows defining specific categories as part of the same Credo.Check, which it can be useful for uses cases where the "searching" algorithm is used for related checks, but with different categories and/or notification levels. For instance, a Credo.Check (*1) I have been implementing recently: it searches for soft-deprecated and forbidden functions (while having `--warning-as-error` enabled in our CI pipelines, so `@deprecated` cannot be used for soft ones):
- Informational Check: Used for recommendations "avoid if possible, port it when you have time", categorized separately (e.g., `:soft_deprecated`, `recommendation`, `advice`, etc), and …

Credo.Check format_issue opts allow a custom category

---

lib/credo/check/consistency/unused_variable_names/collector.ex
test/credo/check/consistency/unused_variable_names_test.exs

While solving ours `{Credo.Check.Consistency.UnusedVariableNames, [force: :meaningful]}` check issues, I noticed that many cases were not being caught by the check, such as:
```elixir
{:ok, _} = fun1()
with {:ok, _} <- fun1(), do: :ok
def fun2([_ | _]) do
end
defmacro __using__(_) do
end
```
This MR adds the missing checks I could notice, so feel free to add/point any other cases we could still be missing.

Add `UnusedVariableNames` missing checks

---

lib/credo/check/refactor/double_boolean_negation.ex
test/credo/check/refactor/double_boolean_negation_test.exs

Currently, Credo.Check.Refactor.DoubleBooleanNegation triggers on "!!foo" and "not not foo".
This extends it to trigger on "!not foo" and "not !foo" as well.

Extend double boolean negation to include '! not' and 'not !'

---

.github/workflows/code-scan-sarif.yml
.github/workflows/housekeeping-bugfix-reproducer.yml
.github/workflows/housekeeping.yml

Got format error in CI I didn't see using Elixir 1.18 in #1190. I'm updating everything in CI here to use the latest elixir/otp versions.

Use latest Elixir and OTP versions in CI

---

lib/credo/check.ex

The docs didn't link correctly with Credo checks in other libraries because there's just a relative ref to the extra page. This PR will autolink the Credo extra pages references as per: https://hexdocs.pm/ex_doc/readme.html#auto-linking
Unfortunately it doesn't seem that ExDoc understands how to link `e:credo:EXTRA_PAGE.html` correctly when used in the same library. The link just becomes `credo/EXTRA_PAGE.html` instead of `EXTRA_PAGE.html` properly because there's nothing in the deps. So I'm only using the autolink when outside Credo.

Link to the credo docs when app is not credo

---

lib/credo/check/refactor/abc_size.ex
test/credo/check/refactor/abc_size_test.exs

- ignore unquote() calls (used in macros)
- always count module attribute call as 1
fixes #1172

fixes for ABCSize check
